// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.transaction.grpc;

public interface SignatureInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transaction.SignatureInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string signer_address = 1;</code>
   * @return The signerAddress.
   */
  java.lang.String getSignerAddress();
  /**
   * <code>string signer_address = 1;</code>
   * @return The bytes for signerAddress.
   */
  com.google.protobuf.ByteString
      getSignerAddressBytes();

  /**
   * <code>string signature = 2;</code>
   * @return The signature.
   */
  java.lang.String getSignature();
  /**
   * <code>string signature = 2;</code>
   * @return The bytes for signature.
   */
  com.google.protobuf.ByteString
      getSignatureBytes();

  /**
   * <code>int64 signed_at = 3;</code>
   * @return The signedAt.
   */
  long getSignedAt();
}
