// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.transaction.grpc;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transaction.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tx_hash = 1;</code>
   * @return The txHash.
   */
  java.lang.String getTxHash();
  /**
   * <code>string tx_hash = 1;</code>
   * @return The bytes for txHash.
   */
  com.google.protobuf.ByteString
      getTxHashBytes();

  /**
   * <code>string from_address = 2;</code>
   * @return The fromAddress.
   */
  java.lang.String getFromAddress();
  /**
   * <code>string from_address = 2;</code>
   * @return The bytes for fromAddress.
   */
  com.google.protobuf.ByteString
      getFromAddressBytes();

  /**
   * <code>string to_address = 3;</code>
   * @return The toAddress.
   */
  java.lang.String getToAddress();
  /**
   * <code>string to_address = 3;</code>
   * @return The bytes for toAddress.
   */
  com.google.protobuf.ByteString
      getToAddressBytes();

  /**
   * <code>string amount = 4;</code>
   * @return The amount.
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 4;</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>string gas_price = 5;</code>
   * @return The gasPrice.
   */
  java.lang.String getGasPrice();
  /**
   * <code>string gas_price = 5;</code>
   * @return The bytes for gasPrice.
   */
  com.google.protobuf.ByteString
      getGasPriceBytes();

  /**
   * <code>string gas_used = 6;</code>
   * @return The gasUsed.
   */
  java.lang.String getGasUsed();
  /**
   * <code>string gas_used = 6;</code>
   * @return The bytes for gasUsed.
   */
  com.google.protobuf.ByteString
      getGasUsedBytes();

  /**
   * <code>.transaction.TransactionStatus status = 7;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.transaction.TransactionStatus status = 7;</code>
   * @return The status.
   */
  com.blockchain.transaction.grpc.TransactionStatus getStatus();

  /**
   * <code>.transaction.TransactionType type = 8;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.transaction.TransactionType type = 8;</code>
   * @return The type.
   */
  com.blockchain.transaction.grpc.TransactionType getType();

  /**
   * <code>int64 block_number = 9;</code>
   * @return The blockNumber.
   */
  long getBlockNumber();

  /**
   * <code>int64 timestamp = 10;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string network = 11;</code>
   * @return The network.
   */
  java.lang.String getNetwork();
  /**
   * <code>string network = 11;</code>
   * @return The bytes for network.
   */
  com.google.protobuf.ByteString
      getNetworkBytes();
}
