// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.transaction.grpc;

/**
 * Protobuf enum {@code transaction.TransactionType}
 */
public enum TransactionType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SEND = 0;</code>
   */
  SEND(0),
  /**
   * <code>RECEIVE = 1;</code>
   */
  RECEIVE(1),
  /**
   * <code>SWAP = 2;</code>
   */
  SWAP(2),
  /**
   * <code>CONTRACT_CALL = 3;</code>
   */
  CONTRACT_CALL(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SEND = 0;</code>
   */
  public static final int SEND_VALUE = 0;
  /**
   * <code>RECEIVE = 1;</code>
   */
  public static final int RECEIVE_VALUE = 1;
  /**
   * <code>SWAP = 2;</code>
   */
  public static final int SWAP_VALUE = 2;
  /**
   * <code>CONTRACT_CALL = 3;</code>
   */
  public static final int CONTRACT_CALL_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TransactionType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TransactionType forNumber(int value) {
    switch (value) {
      case 0: return SEND;
      case 1: return RECEIVE;
      case 2: return SWAP;
      case 3: return CONTRACT_CALL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TransactionType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TransactionType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TransactionType>() {
          public TransactionType findValueByNumber(int number) {
            return TransactionType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.blockchain.transaction.grpc.TransactionProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final TransactionType[] VALUES = values();

  public static TransactionType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TransactionType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:transaction.TransactionType)
}

