// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.blockchain.grpc;

public interface GasPricesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.GasPricesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string slow = 1;</code>
   * @return The slow.
   */
  java.lang.String getSlow();
  /**
   * <code>string slow = 1;</code>
   * @return The bytes for slow.
   */
  com.google.protobuf.ByteString
      getSlowBytes();

  /**
   * <code>string standard = 2;</code>
   * @return The standard.
   */
  java.lang.String getStandard();
  /**
   * <code>string standard = 2;</code>
   * @return The bytes for standard.
   */
  com.google.protobuf.ByteString
      getStandardBytes();

  /**
   * <code>string fast = 3;</code>
   * @return The fast.
   */
  java.lang.String getFast();
  /**
   * <code>string fast = 3;</code>
   * @return The bytes for fast.
   */
  com.google.protobuf.ByteString
      getFastBytes();

  /**
   * <code>string instant = 4;</code>
   * @return The instant.
   */
  java.lang.String getInstant();
  /**
   * <code>string instant = 4;</code>
   * @return The bytes for instant.
   */
  com.google.protobuf.ByteString
      getInstantBytes();

  /**
   * <code>string base_fee = 5;</code>
   * @return The baseFee.
   */
  java.lang.String getBaseFee();
  /**
   * <code>string base_fee = 5;</code>
   * @return The bytes for baseFee.
   */
  com.google.protobuf.ByteString
      getBaseFeeBytes();

  /**
   * <code>string network = 6;</code>
   * @return The network.
   */
  java.lang.String getNetwork();
  /**
   * <code>string network = 6;</code>
   * @return The bytes for network.
   */
  com.google.protobuf.ByteString
      getNetworkBytes();

  /**
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
