// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.blockchain.grpc;

/**
 * Protobuf type {@code blockchain.GasPricesResponse}
 */
public final class GasPricesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:blockchain.GasPricesResponse)
    GasPricesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GasPricesResponse.newBuilder() to construct.
  private GasPricesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GasPricesResponse() {
    slow_ = "";
    standard_ = "";
    fast_ = "";
    instant_ = "";
    baseFee_ = "";
    network_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GasPricesResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_GasPricesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_GasPricesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.blockchain.blockchain.grpc.GasPricesResponse.class, com.blockchain.blockchain.grpc.GasPricesResponse.Builder.class);
  }

  public static final int SLOW_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object slow_ = "";
  /**
   * <code>string slow = 1;</code>
   * @return The slow.
   */
  @java.lang.Override
  public java.lang.String getSlow() {
    java.lang.Object ref = slow_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      slow_ = s;
      return s;
    }
  }
  /**
   * <code>string slow = 1;</code>
   * @return The bytes for slow.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSlowBytes() {
    java.lang.Object ref = slow_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      slow_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STANDARD_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object standard_ = "";
  /**
   * <code>string standard = 2;</code>
   * @return The standard.
   */
  @java.lang.Override
  public java.lang.String getStandard() {
    java.lang.Object ref = standard_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      standard_ = s;
      return s;
    }
  }
  /**
   * <code>string standard = 2;</code>
   * @return The bytes for standard.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStandardBytes() {
    java.lang.Object ref = standard_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      standard_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FAST_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fast_ = "";
  /**
   * <code>string fast = 3;</code>
   * @return The fast.
   */
  @java.lang.Override
  public java.lang.String getFast() {
    java.lang.Object ref = fast_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fast_ = s;
      return s;
    }
  }
  /**
   * <code>string fast = 3;</code>
   * @return The bytes for fast.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFastBytes() {
    java.lang.Object ref = fast_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fast_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSTANT_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object instant_ = "";
  /**
   * <code>string instant = 4;</code>
   * @return The instant.
   */
  @java.lang.Override
  public java.lang.String getInstant() {
    java.lang.Object ref = instant_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      instant_ = s;
      return s;
    }
  }
  /**
   * <code>string instant = 4;</code>
   * @return The bytes for instant.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInstantBytes() {
    java.lang.Object ref = instant_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      instant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BASE_FEE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object baseFee_ = "";
  /**
   * <code>string base_fee = 5;</code>
   * @return The baseFee.
   */
  @java.lang.Override
  public java.lang.String getBaseFee() {
    java.lang.Object ref = baseFee_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      baseFee_ = s;
      return s;
    }
  }
  /**
   * <code>string base_fee = 5;</code>
   * @return The bytes for baseFee.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBaseFeeBytes() {
    java.lang.Object ref = baseFee_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      baseFee_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NETWORK_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object network_ = "";
  /**
   * <code>string network = 6;</code>
   * @return The network.
   */
  @java.lang.Override
  public java.lang.String getNetwork() {
    java.lang.Object ref = network_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      network_ = s;
      return s;
    }
  }
  /**
   * <code>string network = 6;</code>
   * @return The bytes for network.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNetworkBytes() {
    java.lang.Object ref = network_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      network_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(slow_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, slow_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(standard_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, standard_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fast_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fast_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instant_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, instant_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseFee_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, baseFee_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(network_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, network_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(7, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(slow_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, slow_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(standard_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, standard_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fast_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fast_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instant_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, instant_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseFee_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, baseFee_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(network_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, network_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.blockchain.blockchain.grpc.GasPricesResponse)) {
      return super.equals(obj);
    }
    com.blockchain.blockchain.grpc.GasPricesResponse other = (com.blockchain.blockchain.grpc.GasPricesResponse) obj;

    if (!getSlow()
        .equals(other.getSlow())) return false;
    if (!getStandard()
        .equals(other.getStandard())) return false;
    if (!getFast()
        .equals(other.getFast())) return false;
    if (!getInstant()
        .equals(other.getInstant())) return false;
    if (!getBaseFee()
        .equals(other.getBaseFee())) return false;
    if (!getNetwork()
        .equals(other.getNetwork())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SLOW_FIELD_NUMBER;
    hash = (53 * hash) + getSlow().hashCode();
    hash = (37 * hash) + STANDARD_FIELD_NUMBER;
    hash = (53 * hash) + getStandard().hashCode();
    hash = (37 * hash) + FAST_FIELD_NUMBER;
    hash = (53 * hash) + getFast().hashCode();
    hash = (37 * hash) + INSTANT_FIELD_NUMBER;
    hash = (53 * hash) + getInstant().hashCode();
    hash = (37 * hash) + BASE_FEE_FIELD_NUMBER;
    hash = (53 * hash) + getBaseFee().hashCode();
    hash = (37 * hash) + NETWORK_FIELD_NUMBER;
    hash = (53 * hash) + getNetwork().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.blockchain.blockchain.grpc.GasPricesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.blockchain.grpc.GasPricesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.GasPricesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.blockchain.grpc.GasPricesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.GasPricesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.blockchain.grpc.GasPricesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.GasPricesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.blockchain.grpc.GasPricesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.blockchain.blockchain.grpc.GasPricesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.blockchain.blockchain.grpc.GasPricesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.GasPricesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.blockchain.grpc.GasPricesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.blockchain.blockchain.grpc.GasPricesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code blockchain.GasPricesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:blockchain.GasPricesResponse)
      com.blockchain.blockchain.grpc.GasPricesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_GasPricesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_GasPricesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blockchain.blockchain.grpc.GasPricesResponse.class, com.blockchain.blockchain.grpc.GasPricesResponse.Builder.class);
    }

    // Construct using com.blockchain.blockchain.grpc.GasPricesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      slow_ = "";
      standard_ = "";
      fast_ = "";
      instant_ = "";
      baseFee_ = "";
      network_ = "";
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_GasPricesResponse_descriptor;
    }

    @java.lang.Override
    public com.blockchain.blockchain.grpc.GasPricesResponse getDefaultInstanceForType() {
      return com.blockchain.blockchain.grpc.GasPricesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.blockchain.blockchain.grpc.GasPricesResponse build() {
      com.blockchain.blockchain.grpc.GasPricesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.blockchain.blockchain.grpc.GasPricesResponse buildPartial() {
      com.blockchain.blockchain.grpc.GasPricesResponse result = new com.blockchain.blockchain.grpc.GasPricesResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.blockchain.blockchain.grpc.GasPricesResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.slow_ = slow_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.standard_ = standard_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.fast_ = fast_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.instant_ = instant_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.baseFee_ = baseFee_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.network_ = network_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.blockchain.blockchain.grpc.GasPricesResponse) {
        return mergeFrom((com.blockchain.blockchain.grpc.GasPricesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.blockchain.blockchain.grpc.GasPricesResponse other) {
      if (other == com.blockchain.blockchain.grpc.GasPricesResponse.getDefaultInstance()) return this;
      if (!other.getSlow().isEmpty()) {
        slow_ = other.slow_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getStandard().isEmpty()) {
        standard_ = other.standard_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getFast().isEmpty()) {
        fast_ = other.fast_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getInstant().isEmpty()) {
        instant_ = other.instant_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getBaseFee().isEmpty()) {
        baseFee_ = other.baseFee_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getNetwork().isEmpty()) {
        network_ = other.network_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              slow_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              standard_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              fast_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              instant_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              baseFee_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              network_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object slow_ = "";
    /**
     * <code>string slow = 1;</code>
     * @return The slow.
     */
    public java.lang.String getSlow() {
      java.lang.Object ref = slow_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        slow_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string slow = 1;</code>
     * @return The bytes for slow.
     */
    public com.google.protobuf.ByteString
        getSlowBytes() {
      java.lang.Object ref = slow_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        slow_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string slow = 1;</code>
     * @param value The slow to set.
     * @return This builder for chaining.
     */
    public Builder setSlow(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      slow_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string slow = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlow() {
      slow_ = getDefaultInstance().getSlow();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string slow = 1;</code>
     * @param value The bytes for slow to set.
     * @return This builder for chaining.
     */
    public Builder setSlowBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      slow_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object standard_ = "";
    /**
     * <code>string standard = 2;</code>
     * @return The standard.
     */
    public java.lang.String getStandard() {
      java.lang.Object ref = standard_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        standard_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string standard = 2;</code>
     * @return The bytes for standard.
     */
    public com.google.protobuf.ByteString
        getStandardBytes() {
      java.lang.Object ref = standard_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        standard_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string standard = 2;</code>
     * @param value The standard to set.
     * @return This builder for chaining.
     */
    public Builder setStandard(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      standard_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string standard = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStandard() {
      standard_ = getDefaultInstance().getStandard();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string standard = 2;</code>
     * @param value The bytes for standard to set.
     * @return This builder for chaining.
     */
    public Builder setStandardBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      standard_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object fast_ = "";
    /**
     * <code>string fast = 3;</code>
     * @return The fast.
     */
    public java.lang.String getFast() {
      java.lang.Object ref = fast_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fast_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fast = 3;</code>
     * @return The bytes for fast.
     */
    public com.google.protobuf.ByteString
        getFastBytes() {
      java.lang.Object ref = fast_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fast_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fast = 3;</code>
     * @param value The fast to set.
     * @return This builder for chaining.
     */
    public Builder setFast(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fast_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string fast = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFast() {
      fast_ = getDefaultInstance().getFast();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string fast = 3;</code>
     * @param value The bytes for fast to set.
     * @return This builder for chaining.
     */
    public Builder setFastBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fast_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object instant_ = "";
    /**
     * <code>string instant = 4;</code>
     * @return The instant.
     */
    public java.lang.String getInstant() {
      java.lang.Object ref = instant_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instant_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string instant = 4;</code>
     * @return The bytes for instant.
     */
    public com.google.protobuf.ByteString
        getInstantBytes() {
      java.lang.Object ref = instant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string instant = 4;</code>
     * @param value The instant to set.
     * @return This builder for chaining.
     */
    public Builder setInstant(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      instant_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string instant = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearInstant() {
      instant_ = getDefaultInstance().getInstant();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string instant = 4;</code>
     * @param value The bytes for instant to set.
     * @return This builder for chaining.
     */
    public Builder setInstantBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      instant_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object baseFee_ = "";
    /**
     * <code>string base_fee = 5;</code>
     * @return The baseFee.
     */
    public java.lang.String getBaseFee() {
      java.lang.Object ref = baseFee_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseFee_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string base_fee = 5;</code>
     * @return The bytes for baseFee.
     */
    public com.google.protobuf.ByteString
        getBaseFeeBytes() {
      java.lang.Object ref = baseFee_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseFee_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string base_fee = 5;</code>
     * @param value The baseFee to set.
     * @return This builder for chaining.
     */
    public Builder setBaseFee(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      baseFee_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string base_fee = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBaseFee() {
      baseFee_ = getDefaultInstance().getBaseFee();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string base_fee = 5;</code>
     * @param value The bytes for baseFee to set.
     * @return This builder for chaining.
     */
    public Builder setBaseFeeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      baseFee_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object network_ = "";
    /**
     * <code>string network = 6;</code>
     * @return The network.
     */
    public java.lang.String getNetwork() {
      java.lang.Object ref = network_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        network_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string network = 6;</code>
     * @return The bytes for network.
     */
    public com.google.protobuf.ByteString
        getNetworkBytes() {
      java.lang.Object ref = network_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        network_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string network = 6;</code>
     * @param value The network to set.
     * @return This builder for chaining.
     */
    public Builder setNetwork(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      network_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string network = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetwork() {
      network_ = getDefaultInstance().getNetwork();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string network = 6;</code>
     * @param value The bytes for network to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      network_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 7;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000040);
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:blockchain.GasPricesResponse)
  }

  // @@protoc_insertion_point(class_scope:blockchain.GasPricesResponse)
  private static final com.blockchain.blockchain.grpc.GasPricesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.blockchain.blockchain.grpc.GasPricesResponse();
  }

  public static com.blockchain.blockchain.grpc.GasPricesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GasPricesResponse>
      PARSER = new com.google.protobuf.AbstractParser<GasPricesResponse>() {
    @java.lang.Override
    public GasPricesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GasPricesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GasPricesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.blockchain.blockchain.grpc.GasPricesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

