// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.blockchain.grpc;

public interface GetBalancesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.GetBalancesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .blockchain.BalanceResponse balances = 1;</code>
   */
  java.util.List<com.blockchain.blockchain.grpc.BalanceResponse> 
      getBalancesList();
  /**
   * <code>repeated .blockchain.BalanceResponse balances = 1;</code>
   */
  com.blockchain.blockchain.grpc.BalanceResponse getBalances(int index);
  /**
   * <code>repeated .blockchain.BalanceResponse balances = 1;</code>
   */
  int getBalancesCount();
  /**
   * <code>repeated .blockchain.BalanceResponse balances = 1;</code>
   */
  java.util.List<? extends com.blockchain.blockchain.grpc.BalanceResponseOrBuilder> 
      getBalancesOrBuilderList();
  /**
   * <code>repeated .blockchain.BalanceResponse balances = 1;</code>
   */
  com.blockchain.blockchain.grpc.BalanceResponseOrBuilder getBalancesOrBuilder(
      int index);
}
