// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.blockchain.grpc;

/**
 * Protobuf type {@code blockchain.NetworkStatusResponse}
 */
public final class NetworkStatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:blockchain.NetworkStatusResponse)
    NetworkStatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NetworkStatusResponse.newBuilder() to construct.
  private NetworkStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NetworkStatusResponse() {
    network_ = "";
    chainId_ = "";
    peerCount_ = "";
    gasPrice_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NetworkStatusResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_NetworkStatusResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_NetworkStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.blockchain.blockchain.grpc.NetworkStatusResponse.class, com.blockchain.blockchain.grpc.NetworkStatusResponse.Builder.class);
  }

  public static final int NETWORK_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object network_ = "";
  /**
   * <code>string network = 1;</code>
   * @return The network.
   */
  @java.lang.Override
  public java.lang.String getNetwork() {
    java.lang.Object ref = network_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      network_ = s;
      return s;
    }
  }
  /**
   * <code>string network = 1;</code>
   * @return The bytes for network.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNetworkBytes() {
    java.lang.Object ref = network_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      network_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHAIN_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object chainId_ = "";
  /**
   * <code>string chain_id = 2;</code>
   * @return The chainId.
   */
  @java.lang.Override
  public java.lang.String getChainId() {
    java.lang.Object ref = chainId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chainId_ = s;
      return s;
    }
  }
  /**
   * <code>string chain_id = 2;</code>
   * @return The bytes for chainId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChainIdBytes() {
    java.lang.Object ref = chainId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chainId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LATEST_BLOCK_FIELD_NUMBER = 3;
  private long latestBlock_ = 0L;
  /**
   * <code>int64 latest_block = 3;</code>
   * @return The latestBlock.
   */
  @java.lang.Override
  public long getLatestBlock() {
    return latestBlock_;
  }

  public static final int PEER_COUNT_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object peerCount_ = "";
  /**
   * <code>string peer_count = 4;</code>
   * @return The peerCount.
   */
  @java.lang.Override
  public java.lang.String getPeerCount() {
    java.lang.Object ref = peerCount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      peerCount_ = s;
      return s;
    }
  }
  /**
   * <code>string peer_count = 4;</code>
   * @return The bytes for peerCount.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPeerCountBytes() {
    java.lang.Object ref = peerCount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      peerCount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_SYNCING_FIELD_NUMBER = 5;
  private boolean isSyncing_ = false;
  /**
   * <code>bool is_syncing = 5;</code>
   * @return The isSyncing.
   */
  @java.lang.Override
  public boolean getIsSyncing() {
    return isSyncing_;
  }

  public static final int GAS_PRICE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gasPrice_ = "";
  /**
   * <code>string gas_price = 6;</code>
   * @return The gasPrice.
   */
  @java.lang.Override
  public java.lang.String getGasPrice() {
    java.lang.Object ref = gasPrice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gasPrice_ = s;
      return s;
    }
  }
  /**
   * <code>string gas_price = 6;</code>
   * @return The bytes for gasPrice.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGasPriceBytes() {
    java.lang.Object ref = gasPrice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gasPrice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(network_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, network_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chainId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, chainId_);
    }
    if (latestBlock_ != 0L) {
      output.writeInt64(3, latestBlock_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(peerCount_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, peerCount_);
    }
    if (isSyncing_ != false) {
      output.writeBool(5, isSyncing_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gasPrice_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, gasPrice_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(7, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(network_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, network_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chainId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, chainId_);
    }
    if (latestBlock_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, latestBlock_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(peerCount_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, peerCount_);
    }
    if (isSyncing_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isSyncing_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gasPrice_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, gasPrice_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.blockchain.blockchain.grpc.NetworkStatusResponse)) {
      return super.equals(obj);
    }
    com.blockchain.blockchain.grpc.NetworkStatusResponse other = (com.blockchain.blockchain.grpc.NetworkStatusResponse) obj;

    if (!getNetwork()
        .equals(other.getNetwork())) return false;
    if (!getChainId()
        .equals(other.getChainId())) return false;
    if (getLatestBlock()
        != other.getLatestBlock()) return false;
    if (!getPeerCount()
        .equals(other.getPeerCount())) return false;
    if (getIsSyncing()
        != other.getIsSyncing()) return false;
    if (!getGasPrice()
        .equals(other.getGasPrice())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NETWORK_FIELD_NUMBER;
    hash = (53 * hash) + getNetwork().hashCode();
    hash = (37 * hash) + CHAIN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChainId().hashCode();
    hash = (37 * hash) + LATEST_BLOCK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLatestBlock());
    hash = (37 * hash) + PEER_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getPeerCount().hashCode();
    hash = (37 * hash) + IS_SYNCING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSyncing());
    hash = (37 * hash) + GAS_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getGasPrice().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.blockchain.blockchain.grpc.NetworkStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.blockchain.grpc.NetworkStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.NetworkStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.blockchain.grpc.NetworkStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.NetworkStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.blockchain.grpc.NetworkStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.NetworkStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.blockchain.grpc.NetworkStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.blockchain.blockchain.grpc.NetworkStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.blockchain.blockchain.grpc.NetworkStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.NetworkStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.blockchain.grpc.NetworkStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.blockchain.blockchain.grpc.NetworkStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code blockchain.NetworkStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:blockchain.NetworkStatusResponse)
      com.blockchain.blockchain.grpc.NetworkStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_NetworkStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_NetworkStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blockchain.blockchain.grpc.NetworkStatusResponse.class, com.blockchain.blockchain.grpc.NetworkStatusResponse.Builder.class);
    }

    // Construct using com.blockchain.blockchain.grpc.NetworkStatusResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      network_ = "";
      chainId_ = "";
      latestBlock_ = 0L;
      peerCount_ = "";
      isSyncing_ = false;
      gasPrice_ = "";
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_NetworkStatusResponse_descriptor;
    }

    @java.lang.Override
    public com.blockchain.blockchain.grpc.NetworkStatusResponse getDefaultInstanceForType() {
      return com.blockchain.blockchain.grpc.NetworkStatusResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.blockchain.blockchain.grpc.NetworkStatusResponse build() {
      com.blockchain.blockchain.grpc.NetworkStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.blockchain.blockchain.grpc.NetworkStatusResponse buildPartial() {
      com.blockchain.blockchain.grpc.NetworkStatusResponse result = new com.blockchain.blockchain.grpc.NetworkStatusResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.blockchain.blockchain.grpc.NetworkStatusResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.network_ = network_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.chainId_ = chainId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.latestBlock_ = latestBlock_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.peerCount_ = peerCount_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isSyncing_ = isSyncing_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.gasPrice_ = gasPrice_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.blockchain.blockchain.grpc.NetworkStatusResponse) {
        return mergeFrom((com.blockchain.blockchain.grpc.NetworkStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.blockchain.blockchain.grpc.NetworkStatusResponse other) {
      if (other == com.blockchain.blockchain.grpc.NetworkStatusResponse.getDefaultInstance()) return this;
      if (!other.getNetwork().isEmpty()) {
        network_ = other.network_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getChainId().isEmpty()) {
        chainId_ = other.chainId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getLatestBlock() != 0L) {
        setLatestBlock(other.getLatestBlock());
      }
      if (!other.getPeerCount().isEmpty()) {
        peerCount_ = other.peerCount_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getIsSyncing() != false) {
        setIsSyncing(other.getIsSyncing());
      }
      if (!other.getGasPrice().isEmpty()) {
        gasPrice_ = other.gasPrice_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              network_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              chainId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              latestBlock_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              peerCount_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              isSyncing_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              gasPrice_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object network_ = "";
    /**
     * <code>string network = 1;</code>
     * @return The network.
     */
    public java.lang.String getNetwork() {
      java.lang.Object ref = network_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        network_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string network = 1;</code>
     * @return The bytes for network.
     */
    public com.google.protobuf.ByteString
        getNetworkBytes() {
      java.lang.Object ref = network_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        network_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string network = 1;</code>
     * @param value The network to set.
     * @return This builder for chaining.
     */
    public Builder setNetwork(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      network_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string network = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetwork() {
      network_ = getDefaultInstance().getNetwork();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string network = 1;</code>
     * @param value The bytes for network to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      network_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object chainId_ = "";
    /**
     * <code>string chain_id = 2;</code>
     * @return The chainId.
     */
    public java.lang.String getChainId() {
      java.lang.Object ref = chainId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chainId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string chain_id = 2;</code>
     * @return The bytes for chainId.
     */
    public com.google.protobuf.ByteString
        getChainIdBytes() {
      java.lang.Object ref = chainId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chainId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chain_id = 2;</code>
     * @param value The chainId to set.
     * @return This builder for chaining.
     */
    public Builder setChainId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      chainId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string chain_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChainId() {
      chainId_ = getDefaultInstance().getChainId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string chain_id = 2;</code>
     * @param value The bytes for chainId to set.
     * @return This builder for chaining.
     */
    public Builder setChainIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      chainId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long latestBlock_ ;
    /**
     * <code>int64 latest_block = 3;</code>
     * @return The latestBlock.
     */
    @java.lang.Override
    public long getLatestBlock() {
      return latestBlock_;
    }
    /**
     * <code>int64 latest_block = 3;</code>
     * @param value The latestBlock to set.
     * @return This builder for chaining.
     */
    public Builder setLatestBlock(long value) {

      latestBlock_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 latest_block = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLatestBlock() {
      bitField0_ = (bitField0_ & ~0x00000004);
      latestBlock_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object peerCount_ = "";
    /**
     * <code>string peer_count = 4;</code>
     * @return The peerCount.
     */
    public java.lang.String getPeerCount() {
      java.lang.Object ref = peerCount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerCount_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string peer_count = 4;</code>
     * @return The bytes for peerCount.
     */
    public com.google.protobuf.ByteString
        getPeerCountBytes() {
      java.lang.Object ref = peerCount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerCount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string peer_count = 4;</code>
     * @param value The peerCount to set.
     * @return This builder for chaining.
     */
    public Builder setPeerCount(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      peerCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string peer_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeerCount() {
      peerCount_ = getDefaultInstance().getPeerCount();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string peer_count = 4;</code>
     * @param value The bytes for peerCount to set.
     * @return This builder for chaining.
     */
    public Builder setPeerCountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      peerCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private boolean isSyncing_ ;
    /**
     * <code>bool is_syncing = 5;</code>
     * @return The isSyncing.
     */
    @java.lang.Override
    public boolean getIsSyncing() {
      return isSyncing_;
    }
    /**
     * <code>bool is_syncing = 5;</code>
     * @param value The isSyncing to set.
     * @return This builder for chaining.
     */
    public Builder setIsSyncing(boolean value) {

      isSyncing_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_syncing = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSyncing() {
      bitField0_ = (bitField0_ & ~0x00000010);
      isSyncing_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object gasPrice_ = "";
    /**
     * <code>string gas_price = 6;</code>
     * @return The gasPrice.
     */
    public java.lang.String getGasPrice() {
      java.lang.Object ref = gasPrice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gasPrice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gas_price = 6;</code>
     * @return The bytes for gasPrice.
     */
    public com.google.protobuf.ByteString
        getGasPriceBytes() {
      java.lang.Object ref = gasPrice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gasPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gas_price = 6;</code>
     * @param value The gasPrice to set.
     * @return This builder for chaining.
     */
    public Builder setGasPrice(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gasPrice_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string gas_price = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGasPrice() {
      gasPrice_ = getDefaultInstance().getGasPrice();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string gas_price = 6;</code>
     * @param value The bytes for gasPrice to set.
     * @return This builder for chaining.
     */
    public Builder setGasPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gasPrice_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 7;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000040);
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:blockchain.NetworkStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:blockchain.NetworkStatusResponse)
  private static final com.blockchain.blockchain.grpc.NetworkStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.blockchain.blockchain.grpc.NetworkStatusResponse();
  }

  public static com.blockchain.blockchain.grpc.NetworkStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NetworkStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<NetworkStatusResponse>() {
    @java.lang.Override
    public NetworkStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NetworkStatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetworkStatusResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.blockchain.blockchain.grpc.NetworkStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

