// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.wallet.grpc;

public interface AddSignerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wallet.AddSignerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wallet_id = 1;</code>
   * @return The walletId.
   */
  java.lang.String getWalletId();
  /**
   * <code>string wallet_id = 1;</code>
   * @return The bytes for walletId.
   */
  com.google.protobuf.ByteString
      getWalletIdBytes();

  /**
   * <code>string signer_address = 2;</code>
   * @return The signerAddress.
   */
  java.lang.String getSignerAddress();
  /**
   * <code>string signer_address = 2;</code>
   * @return The bytes for signerAddress.
   */
  com.google.protobuf.ByteString
      getSignerAddressBytes();

  /**
   * <code>string signer_name = 3;</code>
   * @return The signerName.
   */
  java.lang.String getSignerName();
  /**
   * <code>string signer_name = 3;</code>
   * @return The bytes for signerName.
   */
  com.google.protobuf.ByteString
      getSignerNameBytes();
}
