// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.wallet.grpc;

/**
 * Protobuf enum {@code wallet.NetworkType}
 */
public enum NetworkType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ETHEREUM_MAINNET = 0;</code>
   */
  ETHEREUM_MAINNET(0),
  /**
   * <code>ETHEREUM_SEPOLIA = 1;</code>
   */
  ETHEREUM_SEPOLIA(1),
  /**
   * <code>POLYGON_MAINNET = 2;</code>
   */
  POLYGON_MAINNET(2),
  /**
   * <code>POLYGON_MUMBAI = 3;</code>
   */
  POLYGON_MUMBAI(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ETHEREUM_MAINNET = 0;</code>
   */
  public static final int ETHEREUM_MAINNET_VALUE = 0;
  /**
   * <code>ETHEREUM_SEPOLIA = 1;</code>
   */
  public static final int ETHEREUM_SEPOLIA_VALUE = 1;
  /**
   * <code>POLYGON_MAINNET = 2;</code>
   */
  public static final int POLYGON_MAINNET_VALUE = 2;
  /**
   * <code>POLYGON_MUMBAI = 3;</code>
   */
  public static final int POLYGON_MUMBAI_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static NetworkType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static NetworkType forNumber(int value) {
    switch (value) {
      case 0: return ETHEREUM_MAINNET;
      case 1: return ETHEREUM_SEPOLIA;
      case 2: return POLYGON_MAINNET;
      case 3: return POLYGON_MUMBAI;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<NetworkType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      NetworkType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<NetworkType>() {
          public NetworkType findValueByNumber(int number) {
            return NetworkType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.blockchain.wallet.grpc.WalletProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final NetworkType[] VALUES = values();

  public static NetworkType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private NetworkType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:wallet.NetworkType)
}

