// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.wallet.grpc;

public interface WalletResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wallet.WalletResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wallet_id = 1;</code>
   * @return The walletId.
   */
  java.lang.String getWalletId();
  /**
   * <code>string wallet_id = 1;</code>
   * @return The bytes for walletId.
   */
  com.google.protobuf.ByteString
      getWalletIdBytes();

  /**
   * <code>string address = 2;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.wallet.WalletType type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.wallet.WalletType type = 4;</code>
   * @return The type.
   */
  com.blockchain.wallet.grpc.WalletType getType();

  /**
   * <code>.wallet.NetworkType network = 5;</code>
   * @return The enum numeric value on the wire for network.
   */
  int getNetworkValue();
  /**
   * <code>.wallet.NetworkType network = 5;</code>
   * @return The network.
   */
  com.blockchain.wallet.grpc.NetworkType getNetwork();

  /**
   * <code>int64 created_at = 6;</code>
   * @return The createdAt.
   */
  long getCreatedAt();

  /**
   * <code>int64 updated_at = 7;</code>
   * @return The updatedAt.
   */
  long getUpdatedAt();
}
