// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.wallet.grpc;

public final class WalletProto {
  private WalletProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_CreateWalletRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_CreateWalletRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_CreateWalletResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_CreateWalletResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_GetWalletRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_GetWalletRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_WalletResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_WalletResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_GetUserWalletsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_GetUserWalletsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_GetUserWalletsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_GetUserWalletsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_ImportWalletRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_ImportWalletRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_CreateMultiSigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_CreateMultiSigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_MultiSigWalletResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_MultiSigWalletResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_Signer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_Signer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_GetMultiSigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_GetMultiSigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_AddSignerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_AddSignerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_RemoveSignerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_RemoveSignerRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014wallet.proto\022\006wallet\"l\n\023CreateWalletRe" +
      "quest\022\017\n\007user_id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022$\n\007" +
      "network\030\003 \001(\0162\023.wallet.NetworkType\022\020\n\010pa" +
      "ssword\030\004 \001(\t\"\224\001\n\024CreateWalletResponse\022\021\n" +
      "\twallet_id\030\001 \001(\t\022\017\n\007address\030\002 \001(\t\022\020\n\010mne" +
      "monic\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\022$\n\007network\030\005 \001" +
      "(\0162\023.wallet.NetworkType\022\022\n\ncreated_at\030\006 " +
      "\001(\003\"%\n\020GetWalletRequest\022\021\n\twallet_id\030\001 \001" +
      "(\t\"\262\001\n\016WalletResponse\022\021\n\twallet_id\030\001 \001(\t" +
      "\022\017\n\007address\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022 \n\004type\030" +
      "\004 \001(\0162\022.wallet.WalletType\022$\n\007network\030\005 \001" +
      "(\0162\023.wallet.NetworkType\022\022\n\ncreated_at\030\006 " +
      "\001(\003\022\022\n\nupdated_at\030\007 \001(\003\"(\n\025GetUserWallet" +
      "sRequest\022\017\n\007user_id\030\001 \001(\t\"A\n\026GetUserWall" +
      "etsResponse\022\'\n\007wallets\030\001 \003(\0132\026.wallet.Wa" +
      "lletResponse\"\246\001\n\023ImportWalletRequest\022\017\n\007" +
      "user_id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022$\n\007network\030\003" +
      " \001(\0162\023.wallet.NetworkType\022\020\n\010password\030\004 " +
      "\001(\t\022\025\n\013private_key\030\005 \001(\tH\000\022\022\n\010mnemonic\030\006" +
      " \001(\tH\000B\r\n\013import_type\"\211\001\n\025CreateMultiSig" +
      "Request\022\017\n\007user_id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022$" +
      "\n\007network\030\003 \001(\0162\023.wallet.NetworkType\022\021\n\t" +
      "threshold\030\004 \001(\005\022\030\n\020signer_addresses\030\005 \003(" +
      "\t\"\317\001\n\026MultiSigWalletResponse\022\021\n\twallet_i" +
      "d\030\001 \001(\t\022\017\n\007address\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022$" +
      "\n\007network\030\004 \001(\0162\023.wallet.NetworkType\022\021\n\t" +
      "threshold\030\005 \001(\005\022\025\n\rtotal_signers\030\006 \001(\005\022\037" +
      "\n\007signers\030\007 \003(\0132\016.wallet.Signer\022\022\n\ncreat" +
      "ed_at\030\010 \001(\003\"9\n\006Signer\022\017\n\007address\030\001 \001(\t\022\014" +
      "\n\004name\030\002 \001(\t\022\020\n\010is_owner\030\003 \001(\010\"\'\n\022GetMul" +
      "tiSigRequest\022\021\n\twallet_id\030\001 \001(\t\"R\n\020AddSi" +
      "gnerRequest\022\021\n\twallet_id\030\001 \001(\t\022\026\n\016signer" +
      "_address\030\002 \001(\t\022\023\n\013signer_name\030\003 \001(\t\"@\n\023R" +
      "emoveSignerRequest\022\021\n\twallet_id\030\001 \001(\t\022\026\n" +
      "\016signer_address\030\002 \001(\t*+\n\nWalletType\022\016\n\nS" +
      "INGLE_SIG\020\000\022\r\n\tMULTI_SIG\020\001*b\n\013NetworkTyp" +
      "e\022\024\n\020ETHEREUM_MAINNET\020\000\022\024\n\020ETHEREUM_SEPO" +
      "LIA\020\001\022\023\n\017POLYGON_MAINNET\020\002\022\022\n\016POLYGON_MU" +
      "MBAI\020\0032\361\004\n\rWalletService\022I\n\014CreateWallet" +
      "\022\033.wallet.CreateWalletRequest\032\034.wallet.C" +
      "reateWalletResponse\022=\n\tGetWallet\022\030.walle" +
      "t.GetWalletRequest\032\026.wallet.WalletRespon" +
      "se\022O\n\016GetUserWallets\022\035.wallet.GetUserWal" +
      "letsRequest\032\036.wallet.GetUserWalletsRespo" +
      "nse\022I\n\014ImportWallet\022\033.wallet.ImportWalle" +
      "tRequest\032\034.wallet.CreateWalletResponse\022U" +
      "\n\024CreateMultiSigWallet\022\035.wallet.CreateMu" +
      "ltiSigRequest\032\036.wallet.MultiSigWalletRes" +
      "ponse\022O\n\021GetMultiSigWallet\022\032.wallet.GetM" +
      "ultiSigRequest\032\036.wallet.MultiSigWalletRe" +
      "sponse\022E\n\tAddSigner\022\030.wallet.AddSignerRe" +
      "quest\032\036.wallet.MultiSigWalletResponse\022K\n" +
      "\014RemoveSigner\022\033.wallet.RemoveSignerReque" +
      "st\032\036.wallet.MultiSigWalletResponseB+\n\032co" +
      "m.blockchain.wallet.grpcB\013WalletProtoP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wallet_CreateWalletRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wallet_CreateWalletRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_CreateWalletRequest_descriptor,
        new java.lang.String[] { "UserId", "Name", "Network", "Password", });
    internal_static_wallet_CreateWalletResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wallet_CreateWalletResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_CreateWalletResponse_descriptor,
        new java.lang.String[] { "WalletId", "Address", "Mnemonic", "Name", "Network", "CreatedAt", });
    internal_static_wallet_GetWalletRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_wallet_GetWalletRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_GetWalletRequest_descriptor,
        new java.lang.String[] { "WalletId", });
    internal_static_wallet_WalletResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_wallet_WalletResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_WalletResponse_descriptor,
        new java.lang.String[] { "WalletId", "Address", "Name", "Type", "Network", "CreatedAt", "UpdatedAt", });
    internal_static_wallet_GetUserWalletsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_wallet_GetUserWalletsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_GetUserWalletsRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_wallet_GetUserWalletsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_wallet_GetUserWalletsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_GetUserWalletsResponse_descriptor,
        new java.lang.String[] { "Wallets", });
    internal_static_wallet_ImportWalletRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_wallet_ImportWalletRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_ImportWalletRequest_descriptor,
        new java.lang.String[] { "UserId", "Name", "Network", "Password", "PrivateKey", "Mnemonic", "ImportType", });
    internal_static_wallet_CreateMultiSigRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_wallet_CreateMultiSigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_CreateMultiSigRequest_descriptor,
        new java.lang.String[] { "UserId", "Name", "Network", "Threshold", "SignerAddresses", });
    internal_static_wallet_MultiSigWalletResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_wallet_MultiSigWalletResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_MultiSigWalletResponse_descriptor,
        new java.lang.String[] { "WalletId", "Address", "Name", "Network", "Threshold", "TotalSigners", "Signers", "CreatedAt", });
    internal_static_wallet_Signer_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_wallet_Signer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_Signer_descriptor,
        new java.lang.String[] { "Address", "Name", "IsOwner", });
    internal_static_wallet_GetMultiSigRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_wallet_GetMultiSigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_GetMultiSigRequest_descriptor,
        new java.lang.String[] { "WalletId", });
    internal_static_wallet_AddSignerRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_wallet_AddSignerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_AddSignerRequest_descriptor,
        new java.lang.String[] { "WalletId", "SignerAddress", "SignerName", });
    internal_static_wallet_RemoveSignerRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_wallet_RemoveSignerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_RemoveSignerRequest_descriptor,
        new java.lang.String[] { "WalletId", "SignerAddress", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
