// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.transaction.grpc;

/**
 * Protobuf type {@code transaction.PendingMultiSigTxResponse}
 */
public final class PendingMultiSigTxResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:transaction.PendingMultiSigTxResponse)
    PendingMultiSigTxResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PendingMultiSigTxResponse.newBuilder() to construct.
  private PendingMultiSigTxResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PendingMultiSigTxResponse() {
    pendingTransactions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PendingMultiSigTxResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.blockchain.transaction.grpc.TransactionProto.internal_static_transaction_PendingMultiSigTxResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.blockchain.transaction.grpc.TransactionProto.internal_static_transaction_PendingMultiSigTxResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.blockchain.transaction.grpc.PendingMultiSigTxResponse.class, com.blockchain.transaction.grpc.PendingMultiSigTxResponse.Builder.class);
  }

  public static final int PENDING_TRANSACTIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.blockchain.transaction.grpc.MultiSigTxResponse> pendingTransactions_;
  /**
   * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.blockchain.transaction.grpc.MultiSigTxResponse> getPendingTransactionsList() {
    return pendingTransactions_;
  }
  /**
   * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.blockchain.transaction.grpc.MultiSigTxResponseOrBuilder> 
      getPendingTransactionsOrBuilderList() {
    return pendingTransactions_;
  }
  /**
   * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
   */
  @java.lang.Override
  public int getPendingTransactionsCount() {
    return pendingTransactions_.size();
  }
  /**
   * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
   */
  @java.lang.Override
  public com.blockchain.transaction.grpc.MultiSigTxResponse getPendingTransactions(int index) {
    return pendingTransactions_.get(index);
  }
  /**
   * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
   */
  @java.lang.Override
  public com.blockchain.transaction.grpc.MultiSigTxResponseOrBuilder getPendingTransactionsOrBuilder(
      int index) {
    return pendingTransactions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < pendingTransactions_.size(); i++) {
      output.writeMessage(1, pendingTransactions_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < pendingTransactions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, pendingTransactions_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.blockchain.transaction.grpc.PendingMultiSigTxResponse)) {
      return super.equals(obj);
    }
    com.blockchain.transaction.grpc.PendingMultiSigTxResponse other = (com.blockchain.transaction.grpc.PendingMultiSigTxResponse) obj;

    if (!getPendingTransactionsList()
        .equals(other.getPendingTransactionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPendingTransactionsCount() > 0) {
      hash = (37 * hash) + PENDING_TRANSACTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getPendingTransactionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.blockchain.transaction.grpc.PendingMultiSigTxResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.transaction.grpc.PendingMultiSigTxResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.transaction.grpc.PendingMultiSigTxResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.transaction.grpc.PendingMultiSigTxResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.transaction.grpc.PendingMultiSigTxResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.transaction.grpc.PendingMultiSigTxResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.transaction.grpc.PendingMultiSigTxResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.transaction.grpc.PendingMultiSigTxResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.blockchain.transaction.grpc.PendingMultiSigTxResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.blockchain.transaction.grpc.PendingMultiSigTxResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blockchain.transaction.grpc.PendingMultiSigTxResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.transaction.grpc.PendingMultiSigTxResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.blockchain.transaction.grpc.PendingMultiSigTxResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code transaction.PendingMultiSigTxResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:transaction.PendingMultiSigTxResponse)
      com.blockchain.transaction.grpc.PendingMultiSigTxResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blockchain.transaction.grpc.TransactionProto.internal_static_transaction_PendingMultiSigTxResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blockchain.transaction.grpc.TransactionProto.internal_static_transaction_PendingMultiSigTxResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blockchain.transaction.grpc.PendingMultiSigTxResponse.class, com.blockchain.transaction.grpc.PendingMultiSigTxResponse.Builder.class);
    }

    // Construct using com.blockchain.transaction.grpc.PendingMultiSigTxResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (pendingTransactionsBuilder_ == null) {
        pendingTransactions_ = java.util.Collections.emptyList();
      } else {
        pendingTransactions_ = null;
        pendingTransactionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.blockchain.transaction.grpc.TransactionProto.internal_static_transaction_PendingMultiSigTxResponse_descriptor;
    }

    @java.lang.Override
    public com.blockchain.transaction.grpc.PendingMultiSigTxResponse getDefaultInstanceForType() {
      return com.blockchain.transaction.grpc.PendingMultiSigTxResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.blockchain.transaction.grpc.PendingMultiSigTxResponse build() {
      com.blockchain.transaction.grpc.PendingMultiSigTxResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.blockchain.transaction.grpc.PendingMultiSigTxResponse buildPartial() {
      com.blockchain.transaction.grpc.PendingMultiSigTxResponse result = new com.blockchain.transaction.grpc.PendingMultiSigTxResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.blockchain.transaction.grpc.PendingMultiSigTxResponse result) {
      if (pendingTransactionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          pendingTransactions_ = java.util.Collections.unmodifiableList(pendingTransactions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.pendingTransactions_ = pendingTransactions_;
      } else {
        result.pendingTransactions_ = pendingTransactionsBuilder_.build();
      }
    }

    private void buildPartial0(com.blockchain.transaction.grpc.PendingMultiSigTxResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.blockchain.transaction.grpc.PendingMultiSigTxResponse) {
        return mergeFrom((com.blockchain.transaction.grpc.PendingMultiSigTxResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.blockchain.transaction.grpc.PendingMultiSigTxResponse other) {
      if (other == com.blockchain.transaction.grpc.PendingMultiSigTxResponse.getDefaultInstance()) return this;
      if (pendingTransactionsBuilder_ == null) {
        if (!other.pendingTransactions_.isEmpty()) {
          if (pendingTransactions_.isEmpty()) {
            pendingTransactions_ = other.pendingTransactions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePendingTransactionsIsMutable();
            pendingTransactions_.addAll(other.pendingTransactions_);
          }
          onChanged();
        }
      } else {
        if (!other.pendingTransactions_.isEmpty()) {
          if (pendingTransactionsBuilder_.isEmpty()) {
            pendingTransactionsBuilder_.dispose();
            pendingTransactionsBuilder_ = null;
            pendingTransactions_ = other.pendingTransactions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            pendingTransactionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPendingTransactionsFieldBuilder() : null;
          } else {
            pendingTransactionsBuilder_.addAllMessages(other.pendingTransactions_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.blockchain.transaction.grpc.MultiSigTxResponse m =
                  input.readMessage(
                      com.blockchain.transaction.grpc.MultiSigTxResponse.parser(),
                      extensionRegistry);
              if (pendingTransactionsBuilder_ == null) {
                ensurePendingTransactionsIsMutable();
                pendingTransactions_.add(m);
              } else {
                pendingTransactionsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.blockchain.transaction.grpc.MultiSigTxResponse> pendingTransactions_ =
      java.util.Collections.emptyList();
    private void ensurePendingTransactionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        pendingTransactions_ = new java.util.ArrayList<com.blockchain.transaction.grpc.MultiSigTxResponse>(pendingTransactions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.blockchain.transaction.grpc.MultiSigTxResponse, com.blockchain.transaction.grpc.MultiSigTxResponse.Builder, com.blockchain.transaction.grpc.MultiSigTxResponseOrBuilder> pendingTransactionsBuilder_;

    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public java.util.List<com.blockchain.transaction.grpc.MultiSigTxResponse> getPendingTransactionsList() {
      if (pendingTransactionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pendingTransactions_);
      } else {
        return pendingTransactionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public int getPendingTransactionsCount() {
      if (pendingTransactionsBuilder_ == null) {
        return pendingTransactions_.size();
      } else {
        return pendingTransactionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public com.blockchain.transaction.grpc.MultiSigTxResponse getPendingTransactions(int index) {
      if (pendingTransactionsBuilder_ == null) {
        return pendingTransactions_.get(index);
      } else {
        return pendingTransactionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public Builder setPendingTransactions(
        int index, com.blockchain.transaction.grpc.MultiSigTxResponse value) {
      if (pendingTransactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePendingTransactionsIsMutable();
        pendingTransactions_.set(index, value);
        onChanged();
      } else {
        pendingTransactionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public Builder setPendingTransactions(
        int index, com.blockchain.transaction.grpc.MultiSigTxResponse.Builder builderForValue) {
      if (pendingTransactionsBuilder_ == null) {
        ensurePendingTransactionsIsMutable();
        pendingTransactions_.set(index, builderForValue.build());
        onChanged();
      } else {
        pendingTransactionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public Builder addPendingTransactions(com.blockchain.transaction.grpc.MultiSigTxResponse value) {
      if (pendingTransactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePendingTransactionsIsMutable();
        pendingTransactions_.add(value);
        onChanged();
      } else {
        pendingTransactionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public Builder addPendingTransactions(
        int index, com.blockchain.transaction.grpc.MultiSigTxResponse value) {
      if (pendingTransactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePendingTransactionsIsMutable();
        pendingTransactions_.add(index, value);
        onChanged();
      } else {
        pendingTransactionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public Builder addPendingTransactions(
        com.blockchain.transaction.grpc.MultiSigTxResponse.Builder builderForValue) {
      if (pendingTransactionsBuilder_ == null) {
        ensurePendingTransactionsIsMutable();
        pendingTransactions_.add(builderForValue.build());
        onChanged();
      } else {
        pendingTransactionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public Builder addPendingTransactions(
        int index, com.blockchain.transaction.grpc.MultiSigTxResponse.Builder builderForValue) {
      if (pendingTransactionsBuilder_ == null) {
        ensurePendingTransactionsIsMutable();
        pendingTransactions_.add(index, builderForValue.build());
        onChanged();
      } else {
        pendingTransactionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public Builder addAllPendingTransactions(
        java.lang.Iterable<? extends com.blockchain.transaction.grpc.MultiSigTxResponse> values) {
      if (pendingTransactionsBuilder_ == null) {
        ensurePendingTransactionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pendingTransactions_);
        onChanged();
      } else {
        pendingTransactionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public Builder clearPendingTransactions() {
      if (pendingTransactionsBuilder_ == null) {
        pendingTransactions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        pendingTransactionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public Builder removePendingTransactions(int index) {
      if (pendingTransactionsBuilder_ == null) {
        ensurePendingTransactionsIsMutable();
        pendingTransactions_.remove(index);
        onChanged();
      } else {
        pendingTransactionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public com.blockchain.transaction.grpc.MultiSigTxResponse.Builder getPendingTransactionsBuilder(
        int index) {
      return getPendingTransactionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public com.blockchain.transaction.grpc.MultiSigTxResponseOrBuilder getPendingTransactionsOrBuilder(
        int index) {
      if (pendingTransactionsBuilder_ == null) {
        return pendingTransactions_.get(index);  } else {
        return pendingTransactionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public java.util.List<? extends com.blockchain.transaction.grpc.MultiSigTxResponseOrBuilder> 
         getPendingTransactionsOrBuilderList() {
      if (pendingTransactionsBuilder_ != null) {
        return pendingTransactionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pendingTransactions_);
      }
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public com.blockchain.transaction.grpc.MultiSigTxResponse.Builder addPendingTransactionsBuilder() {
      return getPendingTransactionsFieldBuilder().addBuilder(
          com.blockchain.transaction.grpc.MultiSigTxResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public com.blockchain.transaction.grpc.MultiSigTxResponse.Builder addPendingTransactionsBuilder(
        int index) {
      return getPendingTransactionsFieldBuilder().addBuilder(
          index, com.blockchain.transaction.grpc.MultiSigTxResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .transaction.MultiSigTxResponse pending_transactions = 1;</code>
     */
    public java.util.List<com.blockchain.transaction.grpc.MultiSigTxResponse.Builder> 
         getPendingTransactionsBuilderList() {
      return getPendingTransactionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.blockchain.transaction.grpc.MultiSigTxResponse, com.blockchain.transaction.grpc.MultiSigTxResponse.Builder, com.blockchain.transaction.grpc.MultiSigTxResponseOrBuilder> 
        getPendingTransactionsFieldBuilder() {
      if (pendingTransactionsBuilder_ == null) {
        pendingTransactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.blockchain.transaction.grpc.MultiSigTxResponse, com.blockchain.transaction.grpc.MultiSigTxResponse.Builder, com.blockchain.transaction.grpc.MultiSigTxResponseOrBuilder>(
                pendingTransactions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        pendingTransactions_ = null;
      }
      return pendingTransactionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:transaction.PendingMultiSigTxResponse)
  }

  // @@protoc_insertion_point(class_scope:transaction.PendingMultiSigTxResponse)
  private static final com.blockchain.transaction.grpc.PendingMultiSigTxResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.blockchain.transaction.grpc.PendingMultiSigTxResponse();
  }

  public static com.blockchain.transaction.grpc.PendingMultiSigTxResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PendingMultiSigTxResponse>
      PARSER = new com.google.protobuf.AbstractParser<PendingMultiSigTxResponse>() {
    @java.lang.Override
    public PendingMultiSigTxResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PendingMultiSigTxResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PendingMultiSigTxResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.blockchain.transaction.grpc.PendingMultiSigTxResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

