// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.transaction.grpc;

public interface SignMultiSigTxRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transaction.SignMultiSigTxRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string multisig_tx_id = 1;</code>
   * @return The multisigTxId.
   */
  java.lang.String getMultisigTxId();
  /**
   * <code>string multisig_tx_id = 1;</code>
   * @return The bytes for multisigTxId.
   */
  com.google.protobuf.ByteString
      getMultisigTxIdBytes();

  /**
   * <code>string signer_address = 2;</code>
   * @return The signerAddress.
   */
  java.lang.String getSignerAddress();
  /**
   * <code>string signer_address = 2;</code>
   * @return The bytes for signerAddress.
   */
  com.google.protobuf.ByteString
      getSignerAddressBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
