// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.transaction.grpc;

/**
 * Protobuf type {@code transaction.TransactionStatusUpdate}
 */
public final class TransactionStatusUpdate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:transaction.TransactionStatusUpdate)
    TransactionStatusUpdateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransactionStatusUpdate.newBuilder() to construct.
  private TransactionStatusUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransactionStatusUpdate() {
    txHash_ = "";
    status_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransactionStatusUpdate();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.blockchain.transaction.grpc.TransactionProto.internal_static_transaction_TransactionStatusUpdate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.blockchain.transaction.grpc.TransactionProto.internal_static_transaction_TransactionStatusUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.blockchain.transaction.grpc.TransactionStatusUpdate.class, com.blockchain.transaction.grpc.TransactionStatusUpdate.Builder.class);
  }

  public static final int TX_HASH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object txHash_ = "";
  /**
   * <code>string tx_hash = 1;</code>
   * @return The txHash.
   */
  @java.lang.Override
  public java.lang.String getTxHash() {
    java.lang.Object ref = txHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      txHash_ = s;
      return s;
    }
  }
  /**
   * <code>string tx_hash = 1;</code>
   * @return The bytes for txHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTxHashBytes() {
    java.lang.Object ref = txHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      txHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_ = 0;
  /**
   * <code>.transaction.TransactionStatus status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.transaction.TransactionStatus status = 2;</code>
   * @return The status.
   */
  @java.lang.Override public com.blockchain.transaction.grpc.TransactionStatus getStatus() {
    com.blockchain.transaction.grpc.TransactionStatus result = com.blockchain.transaction.grpc.TransactionStatus.forNumber(status_);
    return result == null ? com.blockchain.transaction.grpc.TransactionStatus.UNRECOGNIZED : result;
  }

  public static final int BLOCK_NUMBER_FIELD_NUMBER = 3;
  private long blockNumber_ = 0L;
  /**
   * <code>int64 block_number = 3;</code>
   * @return The blockNumber.
   */
  @java.lang.Override
  public long getBlockNumber() {
    return blockNumber_;
  }

  public static final int CONFIRMATIONS_FIELD_NUMBER = 4;
  private int confirmations_ = 0;
  /**
   * <code>int32 confirmations = 4;</code>
   * @return The confirmations.
   */
  @java.lang.Override
  public int getConfirmations() {
    return confirmations_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 5;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(txHash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, txHash_);
    }
    if (status_ != com.blockchain.transaction.grpc.TransactionStatus.PENDING.getNumber()) {
      output.writeEnum(2, status_);
    }
    if (blockNumber_ != 0L) {
      output.writeInt64(3, blockNumber_);
    }
    if (confirmations_ != 0) {
      output.writeInt32(4, confirmations_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(5, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(txHash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, txHash_);
    }
    if (status_ != com.blockchain.transaction.grpc.TransactionStatus.PENDING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    if (blockNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, blockNumber_);
    }
    if (confirmations_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, confirmations_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.blockchain.transaction.grpc.TransactionStatusUpdate)) {
      return super.equals(obj);
    }
    com.blockchain.transaction.grpc.TransactionStatusUpdate other = (com.blockchain.transaction.grpc.TransactionStatusUpdate) obj;

    if (!getTxHash()
        .equals(other.getTxHash())) return false;
    if (status_ != other.status_) return false;
    if (getBlockNumber()
        != other.getBlockNumber()) return false;
    if (getConfirmations()
        != other.getConfirmations()) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TX_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getTxHash().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + BLOCK_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlockNumber());
    hash = (37 * hash) + CONFIRMATIONS_FIELD_NUMBER;
    hash = (53 * hash) + getConfirmations();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.blockchain.transaction.grpc.TransactionStatusUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.transaction.grpc.TransactionStatusUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.transaction.grpc.TransactionStatusUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.transaction.grpc.TransactionStatusUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.transaction.grpc.TransactionStatusUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.transaction.grpc.TransactionStatusUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.transaction.grpc.TransactionStatusUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.transaction.grpc.TransactionStatusUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.blockchain.transaction.grpc.TransactionStatusUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.blockchain.transaction.grpc.TransactionStatusUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blockchain.transaction.grpc.TransactionStatusUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.transaction.grpc.TransactionStatusUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.blockchain.transaction.grpc.TransactionStatusUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code transaction.TransactionStatusUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:transaction.TransactionStatusUpdate)
      com.blockchain.transaction.grpc.TransactionStatusUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blockchain.transaction.grpc.TransactionProto.internal_static_transaction_TransactionStatusUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blockchain.transaction.grpc.TransactionProto.internal_static_transaction_TransactionStatusUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blockchain.transaction.grpc.TransactionStatusUpdate.class, com.blockchain.transaction.grpc.TransactionStatusUpdate.Builder.class);
    }

    // Construct using com.blockchain.transaction.grpc.TransactionStatusUpdate.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      txHash_ = "";
      status_ = 0;
      blockNumber_ = 0L;
      confirmations_ = 0;
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.blockchain.transaction.grpc.TransactionProto.internal_static_transaction_TransactionStatusUpdate_descriptor;
    }

    @java.lang.Override
    public com.blockchain.transaction.grpc.TransactionStatusUpdate getDefaultInstanceForType() {
      return com.blockchain.transaction.grpc.TransactionStatusUpdate.getDefaultInstance();
    }

    @java.lang.Override
    public com.blockchain.transaction.grpc.TransactionStatusUpdate build() {
      com.blockchain.transaction.grpc.TransactionStatusUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.blockchain.transaction.grpc.TransactionStatusUpdate buildPartial() {
      com.blockchain.transaction.grpc.TransactionStatusUpdate result = new com.blockchain.transaction.grpc.TransactionStatusUpdate(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.blockchain.transaction.grpc.TransactionStatusUpdate result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.txHash_ = txHash_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.blockNumber_ = blockNumber_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.confirmations_ = confirmations_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.blockchain.transaction.grpc.TransactionStatusUpdate) {
        return mergeFrom((com.blockchain.transaction.grpc.TransactionStatusUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.blockchain.transaction.grpc.TransactionStatusUpdate other) {
      if (other == com.blockchain.transaction.grpc.TransactionStatusUpdate.getDefaultInstance()) return this;
      if (!other.getTxHash().isEmpty()) {
        txHash_ = other.txHash_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getBlockNumber() != 0L) {
        setBlockNumber(other.getBlockNumber());
      }
      if (other.getConfirmations() != 0) {
        setConfirmations(other.getConfirmations());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              txHash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              blockNumber_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              confirmations_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object txHash_ = "";
    /**
     * <code>string tx_hash = 1;</code>
     * @return The txHash.
     */
    public java.lang.String getTxHash() {
      java.lang.Object ref = txHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tx_hash = 1;</code>
     * @return The bytes for txHash.
     */
    public com.google.protobuf.ByteString
        getTxHashBytes() {
      java.lang.Object ref = txHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tx_hash = 1;</code>
     * @param value The txHash to set.
     * @return This builder for chaining.
     */
    public Builder setTxHash(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      txHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string tx_hash = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTxHash() {
      txHash_ = getDefaultInstance().getTxHash();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string tx_hash = 1;</code>
     * @param value The bytes for txHash to set.
     * @return This builder for chaining.
     */
    public Builder setTxHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      txHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.transaction.TransactionStatus status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.transaction.TransactionStatus status = 2;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.transaction.TransactionStatus status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.blockchain.transaction.grpc.TransactionStatus getStatus() {
      com.blockchain.transaction.grpc.TransactionStatus result = com.blockchain.transaction.grpc.TransactionStatus.forNumber(status_);
      return result == null ? com.blockchain.transaction.grpc.TransactionStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.transaction.TransactionStatus status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.blockchain.transaction.grpc.TransactionStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.transaction.TransactionStatus status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      status_ = 0;
      onChanged();
      return this;
    }

    private long blockNumber_ ;
    /**
     * <code>int64 block_number = 3;</code>
     * @return The blockNumber.
     */
    @java.lang.Override
    public long getBlockNumber() {
      return blockNumber_;
    }
    /**
     * <code>int64 block_number = 3;</code>
     * @param value The blockNumber to set.
     * @return This builder for chaining.
     */
    public Builder setBlockNumber(long value) {

      blockNumber_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 block_number = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockNumber() {
      bitField0_ = (bitField0_ & ~0x00000004);
      blockNumber_ = 0L;
      onChanged();
      return this;
    }

    private int confirmations_ ;
    /**
     * <code>int32 confirmations = 4;</code>
     * @return The confirmations.
     */
    @java.lang.Override
    public int getConfirmations() {
      return confirmations_;
    }
    /**
     * <code>int32 confirmations = 4;</code>
     * @param value The confirmations to set.
     * @return This builder for chaining.
     */
    public Builder setConfirmations(int value) {

      confirmations_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 confirmations = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfirmations() {
      bitField0_ = (bitField0_ & ~0x00000008);
      confirmations_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 5;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 5;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000010);
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:transaction.TransactionStatusUpdate)
  }

  // @@protoc_insertion_point(class_scope:transaction.TransactionStatusUpdate)
  private static final com.blockchain.transaction.grpc.TransactionStatusUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.blockchain.transaction.grpc.TransactionStatusUpdate();
  }

  public static com.blockchain.transaction.grpc.TransactionStatusUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionStatusUpdate>
      PARSER = new com.google.protobuf.AbstractParser<TransactionStatusUpdate>() {
    @java.lang.Override
    public TransactionStatusUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TransactionStatusUpdate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionStatusUpdate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.blockchain.transaction.grpc.TransactionStatusUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

