// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.blockchain.grpc;

public interface BalanceUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.BalanceUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string old_balance = 2;</code>
   * @return The oldBalance.
   */
  java.lang.String getOldBalance();
  /**
   * <code>string old_balance = 2;</code>
   * @return The bytes for oldBalance.
   */
  com.google.protobuf.ByteString
      getOldBalanceBytes();

  /**
   * <code>string new_balance = 3;</code>
   * @return The newBalance.
   */
  java.lang.String getNewBalance();
  /**
   * <code>string new_balance = 3;</code>
   * @return The bytes for newBalance.
   */
  com.google.protobuf.ByteString
      getNewBalanceBytes();

  /**
   * <code>string change = 4;</code>
   * @return The change.
   */
  java.lang.String getChange();
  /**
   * <code>string change = 4;</code>
   * @return The bytes for change.
   */
  com.google.protobuf.ByteString
      getChangeBytes();

  /**
   * <code>string tx_hash = 5;</code>
   * @return The txHash.
   */
  java.lang.String getTxHash();
  /**
   * <code>string tx_hash = 5;</code>
   * @return The bytes for txHash.
   */
  com.google.protobuf.ByteString
      getTxHashBytes();

  /**
   * <code>int64 block_number = 6;</code>
   * @return The blockNumber.
   */
  long getBlockNumber();

  /**
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
