// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.blockchain.grpc;

/**
 * Protobuf type {@code blockchain.BlockUpdate}
 */
public final class BlockUpdate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:blockchain.BlockUpdate)
    BlockUpdateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlockUpdate.newBuilder() to construct.
  private BlockUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlockUpdate() {
    blockHash_ = "";
    gasUsed_ = "";
    gasLimit_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BlockUpdate();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_BlockUpdate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_BlockUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.blockchain.blockchain.grpc.BlockUpdate.class, com.blockchain.blockchain.grpc.BlockUpdate.Builder.class);
  }

  public static final int BLOCK_NUMBER_FIELD_NUMBER = 1;
  private long blockNumber_ = 0L;
  /**
   * <code>int64 block_number = 1;</code>
   * @return The blockNumber.
   */
  @java.lang.Override
  public long getBlockNumber() {
    return blockNumber_;
  }

  public static final int BLOCK_HASH_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object blockHash_ = "";
  /**
   * <code>string block_hash = 2;</code>
   * @return The blockHash.
   */
  @java.lang.Override
  public java.lang.String getBlockHash() {
    java.lang.Object ref = blockHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      blockHash_ = s;
      return s;
    }
  }
  /**
   * <code>string block_hash = 2;</code>
   * @return The bytes for blockHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBlockHashBytes() {
    java.lang.Object ref = blockHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      blockHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTION_COUNT_FIELD_NUMBER = 3;
  private int transactionCount_ = 0;
  /**
   * <code>int32 transaction_count = 3;</code>
   * @return The transactionCount.
   */
  @java.lang.Override
  public int getTransactionCount() {
    return transactionCount_;
  }

  public static final int GAS_USED_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gasUsed_ = "";
  /**
   * <code>string gas_used = 4;</code>
   * @return The gasUsed.
   */
  @java.lang.Override
  public java.lang.String getGasUsed() {
    java.lang.Object ref = gasUsed_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gasUsed_ = s;
      return s;
    }
  }
  /**
   * <code>string gas_used = 4;</code>
   * @return The bytes for gasUsed.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGasUsedBytes() {
    java.lang.Object ref = gasUsed_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gasUsed_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GAS_LIMIT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gasLimit_ = "";
  /**
   * <code>string gas_limit = 5;</code>
   * @return The gasLimit.
   */
  @java.lang.Override
  public java.lang.String getGasLimit() {
    java.lang.Object ref = gasLimit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gasLimit_ = s;
      return s;
    }
  }
  /**
   * <code>string gas_limit = 5;</code>
   * @return The bytes for gasLimit.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGasLimitBytes() {
    java.lang.Object ref = gasLimit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gasLimit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (blockNumber_ != 0L) {
      output.writeInt64(1, blockNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockHash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, blockHash_);
    }
    if (transactionCount_ != 0) {
      output.writeInt32(3, transactionCount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gasUsed_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gasUsed_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gasLimit_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, gasLimit_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(6, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (blockNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, blockNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockHash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, blockHash_);
    }
    if (transactionCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, transactionCount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gasUsed_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gasUsed_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gasLimit_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, gasLimit_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.blockchain.blockchain.grpc.BlockUpdate)) {
      return super.equals(obj);
    }
    com.blockchain.blockchain.grpc.BlockUpdate other = (com.blockchain.blockchain.grpc.BlockUpdate) obj;

    if (getBlockNumber()
        != other.getBlockNumber()) return false;
    if (!getBlockHash()
        .equals(other.getBlockHash())) return false;
    if (getTransactionCount()
        != other.getTransactionCount()) return false;
    if (!getGasUsed()
        .equals(other.getGasUsed())) return false;
    if (!getGasLimit()
        .equals(other.getGasLimit())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLOCK_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlockNumber());
    hash = (37 * hash) + BLOCK_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getBlockHash().hashCode();
    hash = (37 * hash) + TRANSACTION_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionCount();
    hash = (37 * hash) + GAS_USED_FIELD_NUMBER;
    hash = (53 * hash) + getGasUsed().hashCode();
    hash = (37 * hash) + GAS_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getGasLimit().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.blockchain.blockchain.grpc.BlockUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.blockchain.grpc.BlockUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.BlockUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.blockchain.grpc.BlockUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.BlockUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.blockchain.grpc.BlockUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.BlockUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.blockchain.grpc.BlockUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.blockchain.blockchain.grpc.BlockUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.blockchain.blockchain.grpc.BlockUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.BlockUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.blockchain.grpc.BlockUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.blockchain.blockchain.grpc.BlockUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code blockchain.BlockUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:blockchain.BlockUpdate)
      com.blockchain.blockchain.grpc.BlockUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_BlockUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_BlockUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blockchain.blockchain.grpc.BlockUpdate.class, com.blockchain.blockchain.grpc.BlockUpdate.Builder.class);
    }

    // Construct using com.blockchain.blockchain.grpc.BlockUpdate.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      blockNumber_ = 0L;
      blockHash_ = "";
      transactionCount_ = 0;
      gasUsed_ = "";
      gasLimit_ = "";
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_BlockUpdate_descriptor;
    }

    @java.lang.Override
    public com.blockchain.blockchain.grpc.BlockUpdate getDefaultInstanceForType() {
      return com.blockchain.blockchain.grpc.BlockUpdate.getDefaultInstance();
    }

    @java.lang.Override
    public com.blockchain.blockchain.grpc.BlockUpdate build() {
      com.blockchain.blockchain.grpc.BlockUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.blockchain.blockchain.grpc.BlockUpdate buildPartial() {
      com.blockchain.blockchain.grpc.BlockUpdate result = new com.blockchain.blockchain.grpc.BlockUpdate(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.blockchain.blockchain.grpc.BlockUpdate result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.blockNumber_ = blockNumber_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.blockHash_ = blockHash_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.transactionCount_ = transactionCount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.gasUsed_ = gasUsed_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.gasLimit_ = gasLimit_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.blockchain.blockchain.grpc.BlockUpdate) {
        return mergeFrom((com.blockchain.blockchain.grpc.BlockUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.blockchain.blockchain.grpc.BlockUpdate other) {
      if (other == com.blockchain.blockchain.grpc.BlockUpdate.getDefaultInstance()) return this;
      if (other.getBlockNumber() != 0L) {
        setBlockNumber(other.getBlockNumber());
      }
      if (!other.getBlockHash().isEmpty()) {
        blockHash_ = other.blockHash_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getTransactionCount() != 0) {
        setTransactionCount(other.getTransactionCount());
      }
      if (!other.getGasUsed().isEmpty()) {
        gasUsed_ = other.gasUsed_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getGasLimit().isEmpty()) {
        gasLimit_ = other.gasLimit_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              blockNumber_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              blockHash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              transactionCount_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              gasUsed_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              gasLimit_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long blockNumber_ ;
    /**
     * <code>int64 block_number = 1;</code>
     * @return The blockNumber.
     */
    @java.lang.Override
    public long getBlockNumber() {
      return blockNumber_;
    }
    /**
     * <code>int64 block_number = 1;</code>
     * @param value The blockNumber to set.
     * @return This builder for chaining.
     */
    public Builder setBlockNumber(long value) {

      blockNumber_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 block_number = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockNumber() {
      bitField0_ = (bitField0_ & ~0x00000001);
      blockNumber_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object blockHash_ = "";
    /**
     * <code>string block_hash = 2;</code>
     * @return The blockHash.
     */
    public java.lang.String getBlockHash() {
      java.lang.Object ref = blockHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blockHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string block_hash = 2;</code>
     * @return The bytes for blockHash.
     */
    public com.google.protobuf.ByteString
        getBlockHashBytes() {
      java.lang.Object ref = blockHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blockHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string block_hash = 2;</code>
     * @param value The blockHash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockHash(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      blockHash_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string block_hash = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockHash() {
      blockHash_ = getDefaultInstance().getBlockHash();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string block_hash = 2;</code>
     * @param value The bytes for blockHash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      blockHash_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int transactionCount_ ;
    /**
     * <code>int32 transaction_count = 3;</code>
     * @return The transactionCount.
     */
    @java.lang.Override
    public int getTransactionCount() {
      return transactionCount_;
    }
    /**
     * <code>int32 transaction_count = 3;</code>
     * @param value The transactionCount to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionCount(int value) {

      transactionCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 transaction_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      transactionCount_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object gasUsed_ = "";
    /**
     * <code>string gas_used = 4;</code>
     * @return The gasUsed.
     */
    public java.lang.String getGasUsed() {
      java.lang.Object ref = gasUsed_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gasUsed_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gas_used = 4;</code>
     * @return The bytes for gasUsed.
     */
    public com.google.protobuf.ByteString
        getGasUsedBytes() {
      java.lang.Object ref = gasUsed_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gasUsed_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gas_used = 4;</code>
     * @param value The gasUsed to set.
     * @return This builder for chaining.
     */
    public Builder setGasUsed(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gasUsed_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string gas_used = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGasUsed() {
      gasUsed_ = getDefaultInstance().getGasUsed();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string gas_used = 4;</code>
     * @param value The bytes for gasUsed to set.
     * @return This builder for chaining.
     */
    public Builder setGasUsedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gasUsed_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object gasLimit_ = "";
    /**
     * <code>string gas_limit = 5;</code>
     * @return The gasLimit.
     */
    public java.lang.String getGasLimit() {
      java.lang.Object ref = gasLimit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gasLimit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gas_limit = 5;</code>
     * @return The bytes for gasLimit.
     */
    public com.google.protobuf.ByteString
        getGasLimitBytes() {
      java.lang.Object ref = gasLimit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gasLimit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gas_limit = 5;</code>
     * @param value The gasLimit to set.
     * @return This builder for chaining.
     */
    public Builder setGasLimit(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gasLimit_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string gas_limit = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGasLimit() {
      gasLimit_ = getDefaultInstance().getGasLimit();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string gas_limit = 5;</code>
     * @param value The bytes for gasLimit to set.
     * @return This builder for chaining.
     */
    public Builder setGasLimitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gasLimit_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000020);
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:blockchain.BlockUpdate)
  }

  // @@protoc_insertion_point(class_scope:blockchain.BlockUpdate)
  private static final com.blockchain.blockchain.grpc.BlockUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.blockchain.blockchain.grpc.BlockUpdate();
  }

  public static com.blockchain.blockchain.grpc.BlockUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlockUpdate>
      PARSER = new com.google.protobuf.AbstractParser<BlockUpdate>() {
    @java.lang.Override
    public BlockUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BlockUpdate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlockUpdate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.blockchain.blockchain.grpc.BlockUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

