// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.blockchain.grpc;

public interface BlockUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.BlockUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 block_number = 1;</code>
   * @return The blockNumber.
   */
  long getBlockNumber();

  /**
   * <code>string block_hash = 2;</code>
   * @return The blockHash.
   */
  java.lang.String getBlockHash();
  /**
   * <code>string block_hash = 2;</code>
   * @return The bytes for blockHash.
   */
  com.google.protobuf.ByteString
      getBlockHashBytes();

  /**
   * <code>int32 transaction_count = 3;</code>
   * @return The transactionCount.
   */
  int getTransactionCount();

  /**
   * <code>string gas_used = 4;</code>
   * @return The gasUsed.
   */
  java.lang.String getGasUsed();
  /**
   * <code>string gas_used = 4;</code>
   * @return The bytes for gasUsed.
   */
  com.google.protobuf.ByteString
      getGasUsedBytes();

  /**
   * <code>string gas_limit = 5;</code>
   * @return The gasLimit.
   */
  java.lang.String getGasLimit();
  /**
   * <code>string gas_limit = 5;</code>
   * @return The bytes for gasLimit.
   */
  com.google.protobuf.ByteString
      getGasLimitBytes();

  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
