// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.blockchain.grpc;

public interface GetTokenBalanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.GetTokenBalanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wallet_address = 1;</code>
   * @return The walletAddress.
   */
  java.lang.String getWalletAddress();
  /**
   * <code>string wallet_address = 1;</code>
   * @return The bytes for walletAddress.
   */
  com.google.protobuf.ByteString
      getWalletAddressBytes();

  /**
   * <code>string token_address = 2;</code>
   * @return The tokenAddress.
   */
  java.lang.String getTokenAddress();
  /**
   * <code>string token_address = 2;</code>
   * @return The bytes for tokenAddress.
   */
  com.google.protobuf.ByteString
      getTokenAddressBytes();

  /**
   * <code>string network = 3;</code>
   * @return The network.
   */
  java.lang.String getNetwork();
  /**
   * <code>string network = 3;</code>
   * @return The bytes for network.
   */
  com.google.protobuf.ByteString
      getNetworkBytes();
}
