// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.transaction.grpc;

public interface CreateMultiSigTxRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transaction.CreateMultiSigTxRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wallet_id = 1;</code>
   * @return The walletId.
   */
  java.lang.String getWalletId();
  /**
   * <code>string wallet_id = 1;</code>
   * @return The bytes for walletId.
   */
  com.google.protobuf.ByteString
      getWalletIdBytes();

  /**
   * <code>string initiator_address = 2;</code>
   * @return The initiatorAddress.
   */
  java.lang.String getInitiatorAddress();
  /**
   * <code>string initiator_address = 2;</code>
   * @return The bytes for initiatorAddress.
   */
  com.google.protobuf.ByteString
      getInitiatorAddressBytes();

  /**
   * <code>string to_address = 3;</code>
   * @return The toAddress.
   */
  java.lang.String getToAddress();
  /**
   * <code>string to_address = 3;</code>
   * @return The bytes for toAddress.
   */
  com.google.protobuf.ByteString
      getToAddressBytes();

  /**
   * <code>string amount = 4;</code>
   * @return The amount.
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 4;</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>string description = 5;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 5;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
