// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.blockchain.grpc;

/**
 * Protobuf type {@code blockchain.BalanceResponse}
 */
public final class BalanceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:blockchain.BalanceResponse)
    BalanceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BalanceResponse.newBuilder() to construct.
  private BalanceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BalanceResponse() {
    address_ = "";
    balanceWei_ = "";
    balanceEth_ = "";
    balanceUsd_ = "";
    network_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BalanceResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_BalanceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_BalanceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.blockchain.blockchain.grpc.BalanceResponse.class, com.blockchain.blockchain.grpc.BalanceResponse.Builder.class);
  }

  public static final int ADDRESS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object address_ = "";
  /**
   * <code>string address = 1;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>string address = 1;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BALANCE_WEI_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object balanceWei_ = "";
  /**
   * <code>string balance_wei = 2;</code>
   * @return The balanceWei.
   */
  @java.lang.Override
  public java.lang.String getBalanceWei() {
    java.lang.Object ref = balanceWei_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      balanceWei_ = s;
      return s;
    }
  }
  /**
   * <code>string balance_wei = 2;</code>
   * @return The bytes for balanceWei.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBalanceWeiBytes() {
    java.lang.Object ref = balanceWei_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      balanceWei_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BALANCE_ETH_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object balanceEth_ = "";
  /**
   * <code>string balance_eth = 3;</code>
   * @return The balanceEth.
   */
  @java.lang.Override
  public java.lang.String getBalanceEth() {
    java.lang.Object ref = balanceEth_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      balanceEth_ = s;
      return s;
    }
  }
  /**
   * <code>string balance_eth = 3;</code>
   * @return The bytes for balanceEth.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBalanceEthBytes() {
    java.lang.Object ref = balanceEth_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      balanceEth_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BALANCE_USD_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object balanceUsd_ = "";
  /**
   * <code>string balance_usd = 4;</code>
   * @return The balanceUsd.
   */
  @java.lang.Override
  public java.lang.String getBalanceUsd() {
    java.lang.Object ref = balanceUsd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      balanceUsd_ = s;
      return s;
    }
  }
  /**
   * <code>string balance_usd = 4;</code>
   * @return The bytes for balanceUsd.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBalanceUsdBytes() {
    java.lang.Object ref = balanceUsd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      balanceUsd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NETWORK_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object network_ = "";
  /**
   * <code>string network = 5;</code>
   * @return The network.
   */
  @java.lang.Override
  public java.lang.String getNetwork() {
    java.lang.Object ref = network_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      network_ = s;
      return s;
    }
  }
  /**
   * <code>string network = 5;</code>
   * @return The bytes for network.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNetworkBytes() {
    java.lang.Object ref = network_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      network_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(balanceWei_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, balanceWei_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(balanceEth_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, balanceEth_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(balanceUsd_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, balanceUsd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(network_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, network_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(6, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(balanceWei_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, balanceWei_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(balanceEth_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, balanceEth_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(balanceUsd_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, balanceUsd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(network_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, network_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.blockchain.blockchain.grpc.BalanceResponse)) {
      return super.equals(obj);
    }
    com.blockchain.blockchain.grpc.BalanceResponse other = (com.blockchain.blockchain.grpc.BalanceResponse) obj;

    if (!getAddress()
        .equals(other.getAddress())) return false;
    if (!getBalanceWei()
        .equals(other.getBalanceWei())) return false;
    if (!getBalanceEth()
        .equals(other.getBalanceEth())) return false;
    if (!getBalanceUsd()
        .equals(other.getBalanceUsd())) return false;
    if (!getNetwork()
        .equals(other.getNetwork())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    hash = (37 * hash) + BALANCE_WEI_FIELD_NUMBER;
    hash = (53 * hash) + getBalanceWei().hashCode();
    hash = (37 * hash) + BALANCE_ETH_FIELD_NUMBER;
    hash = (53 * hash) + getBalanceEth().hashCode();
    hash = (37 * hash) + BALANCE_USD_FIELD_NUMBER;
    hash = (53 * hash) + getBalanceUsd().hashCode();
    hash = (37 * hash) + NETWORK_FIELD_NUMBER;
    hash = (53 * hash) + getNetwork().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.blockchain.blockchain.grpc.BalanceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.blockchain.grpc.BalanceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.BalanceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.blockchain.grpc.BalanceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.BalanceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.blockchain.grpc.BalanceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.BalanceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.blockchain.grpc.BalanceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.blockchain.blockchain.grpc.BalanceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.blockchain.blockchain.grpc.BalanceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blockchain.blockchain.grpc.BalanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.blockchain.grpc.BalanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.blockchain.blockchain.grpc.BalanceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code blockchain.BalanceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:blockchain.BalanceResponse)
      com.blockchain.blockchain.grpc.BalanceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_BalanceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_BalanceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blockchain.blockchain.grpc.BalanceResponse.class, com.blockchain.blockchain.grpc.BalanceResponse.Builder.class);
    }

    // Construct using com.blockchain.blockchain.grpc.BalanceResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      address_ = "";
      balanceWei_ = "";
      balanceEth_ = "";
      balanceUsd_ = "";
      network_ = "";
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.blockchain.blockchain.grpc.BlockchainProto.internal_static_blockchain_BalanceResponse_descriptor;
    }

    @java.lang.Override
    public com.blockchain.blockchain.grpc.BalanceResponse getDefaultInstanceForType() {
      return com.blockchain.blockchain.grpc.BalanceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.blockchain.blockchain.grpc.BalanceResponse build() {
      com.blockchain.blockchain.grpc.BalanceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.blockchain.blockchain.grpc.BalanceResponse buildPartial() {
      com.blockchain.blockchain.grpc.BalanceResponse result = new com.blockchain.blockchain.grpc.BalanceResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.blockchain.blockchain.grpc.BalanceResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.address_ = address_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.balanceWei_ = balanceWei_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.balanceEth_ = balanceEth_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.balanceUsd_ = balanceUsd_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.network_ = network_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.blockchain.blockchain.grpc.BalanceResponse) {
        return mergeFrom((com.blockchain.blockchain.grpc.BalanceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.blockchain.blockchain.grpc.BalanceResponse other) {
      if (other == com.blockchain.blockchain.grpc.BalanceResponse.getDefaultInstance()) return this;
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getBalanceWei().isEmpty()) {
        balanceWei_ = other.balanceWei_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getBalanceEth().isEmpty()) {
        balanceEth_ = other.balanceEth_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getBalanceUsd().isEmpty()) {
        balanceUsd_ = other.balanceUsd_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getNetwork().isEmpty()) {
        network_ = other.network_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              address_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              balanceWei_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              balanceEth_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              balanceUsd_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              network_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object address_ = "";
    /**
     * <code>string address = 1;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string address = 1;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string address = 1;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      address_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string address = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      address_ = getDefaultInstance().getAddress();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string address = 1;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      address_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object balanceWei_ = "";
    /**
     * <code>string balance_wei = 2;</code>
     * @return The balanceWei.
     */
    public java.lang.String getBalanceWei() {
      java.lang.Object ref = balanceWei_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        balanceWei_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string balance_wei = 2;</code>
     * @return The bytes for balanceWei.
     */
    public com.google.protobuf.ByteString
        getBalanceWeiBytes() {
      java.lang.Object ref = balanceWei_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        balanceWei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string balance_wei = 2;</code>
     * @param value The balanceWei to set.
     * @return This builder for chaining.
     */
    public Builder setBalanceWei(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      balanceWei_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string balance_wei = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBalanceWei() {
      balanceWei_ = getDefaultInstance().getBalanceWei();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string balance_wei = 2;</code>
     * @param value The bytes for balanceWei to set.
     * @return This builder for chaining.
     */
    public Builder setBalanceWeiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      balanceWei_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object balanceEth_ = "";
    /**
     * <code>string balance_eth = 3;</code>
     * @return The balanceEth.
     */
    public java.lang.String getBalanceEth() {
      java.lang.Object ref = balanceEth_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        balanceEth_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string balance_eth = 3;</code>
     * @return The bytes for balanceEth.
     */
    public com.google.protobuf.ByteString
        getBalanceEthBytes() {
      java.lang.Object ref = balanceEth_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        balanceEth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string balance_eth = 3;</code>
     * @param value The balanceEth to set.
     * @return This builder for chaining.
     */
    public Builder setBalanceEth(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      balanceEth_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string balance_eth = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBalanceEth() {
      balanceEth_ = getDefaultInstance().getBalanceEth();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string balance_eth = 3;</code>
     * @param value The bytes for balanceEth to set.
     * @return This builder for chaining.
     */
    public Builder setBalanceEthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      balanceEth_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object balanceUsd_ = "";
    /**
     * <code>string balance_usd = 4;</code>
     * @return The balanceUsd.
     */
    public java.lang.String getBalanceUsd() {
      java.lang.Object ref = balanceUsd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        balanceUsd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string balance_usd = 4;</code>
     * @return The bytes for balanceUsd.
     */
    public com.google.protobuf.ByteString
        getBalanceUsdBytes() {
      java.lang.Object ref = balanceUsd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        balanceUsd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string balance_usd = 4;</code>
     * @param value The balanceUsd to set.
     * @return This builder for chaining.
     */
    public Builder setBalanceUsd(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      balanceUsd_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string balance_usd = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBalanceUsd() {
      balanceUsd_ = getDefaultInstance().getBalanceUsd();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string balance_usd = 4;</code>
     * @param value The bytes for balanceUsd to set.
     * @return This builder for chaining.
     */
    public Builder setBalanceUsdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      balanceUsd_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object network_ = "";
    /**
     * <code>string network = 5;</code>
     * @return The network.
     */
    public java.lang.String getNetwork() {
      java.lang.Object ref = network_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        network_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string network = 5;</code>
     * @return The bytes for network.
     */
    public com.google.protobuf.ByteString
        getNetworkBytes() {
      java.lang.Object ref = network_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        network_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string network = 5;</code>
     * @param value The network to set.
     * @return This builder for chaining.
     */
    public Builder setNetwork(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      network_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string network = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetwork() {
      network_ = getDefaultInstance().getNetwork();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string network = 5;</code>
     * @param value The bytes for network to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      network_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000020);
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:blockchain.BalanceResponse)
  }

  // @@protoc_insertion_point(class_scope:blockchain.BalanceResponse)
  private static final com.blockchain.blockchain.grpc.BalanceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.blockchain.blockchain.grpc.BalanceResponse();
  }

  public static com.blockchain.blockchain.grpc.BalanceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BalanceResponse>
      PARSER = new com.google.protobuf.AbstractParser<BalanceResponse>() {
    @java.lang.Override
    public BalanceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BalanceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BalanceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.blockchain.blockchain.grpc.BalanceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

