// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.blockchain.grpc;

public interface NetworkStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blockchain.NetworkStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string network = 1;</code>
   * @return The network.
   */
  java.lang.String getNetwork();
  /**
   * <code>string network = 1;</code>
   * @return The bytes for network.
   */
  com.google.protobuf.ByteString
      getNetworkBytes();

  /**
   * <code>string chain_id = 2;</code>
   * @return The chainId.
   */
  java.lang.String getChainId();
  /**
   * <code>string chain_id = 2;</code>
   * @return The bytes for chainId.
   */
  com.google.protobuf.ByteString
      getChainIdBytes();

  /**
   * <code>int64 latest_block = 3;</code>
   * @return The latestBlock.
   */
  long getLatestBlock();

  /**
   * <code>string peer_count = 4;</code>
   * @return The peerCount.
   */
  java.lang.String getPeerCount();
  /**
   * <code>string peer_count = 4;</code>
   * @return The bytes for peerCount.
   */
  com.google.protobuf.ByteString
      getPeerCountBytes();

  /**
   * <code>bool is_syncing = 5;</code>
   * @return The isSyncing.
   */
  boolean getIsSyncing();

  /**
   * <code>string gas_price = 6;</code>
   * @return The gasPrice.
   */
  java.lang.String getGasPrice();
  /**
   * <code>string gas_price = 6;</code>
   * @return The bytes for gasPrice.
   */
  com.google.protobuf.ByteString
      getGasPriceBytes();

  /**
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
