// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.wallet.grpc;

public interface CreateMultiSigRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wallet.CreateMultiSigRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.wallet.NetworkType network = 3;</code>
   * @return The enum numeric value on the wire for network.
   */
  int getNetworkValue();
  /**
   * <code>.wallet.NetworkType network = 3;</code>
   * @return The network.
   */
  com.blockchain.wallet.grpc.NetworkType getNetwork();

  /**
   * <pre>
   * Number of required signatures
   * </pre>
   *
   * <code>int32 threshold = 4;</code>
   * @return The threshold.
   */
  int getThreshold();

  /**
   * <code>repeated string signer_addresses = 5;</code>
   * @return A list containing the signerAddresses.
   */
  java.util.List<java.lang.String>
      getSignerAddressesList();
  /**
   * <code>repeated string signer_addresses = 5;</code>
   * @return The count of signerAddresses.
   */
  int getSignerAddressesCount();
  /**
   * <code>repeated string signer_addresses = 5;</code>
   * @param index The index of the element to return.
   * @return The signerAddresses at the given index.
   */
  java.lang.String getSignerAddresses(int index);
  /**
   * <code>repeated string signer_addresses = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the signerAddresses at the given index.
   */
  com.google.protobuf.ByteString
      getSignerAddressesBytes(int index);
}
