// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.wallet.grpc;

/**
 * Protobuf type {@code wallet.GetUserWalletsResponse}
 */
public final class GetUserWalletsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wallet.GetUserWalletsResponse)
    GetUserWalletsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetUserWalletsResponse.newBuilder() to construct.
  private GetUserWalletsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetUserWalletsResponse() {
    wallets_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetUserWalletsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.blockchain.wallet.grpc.WalletProto.internal_static_wallet_GetUserWalletsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.blockchain.wallet.grpc.WalletProto.internal_static_wallet_GetUserWalletsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.blockchain.wallet.grpc.GetUserWalletsResponse.class, com.blockchain.wallet.grpc.GetUserWalletsResponse.Builder.class);
  }

  public static final int WALLETS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.blockchain.wallet.grpc.WalletResponse> wallets_;
  /**
   * <code>repeated .wallet.WalletResponse wallets = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.blockchain.wallet.grpc.WalletResponse> getWalletsList() {
    return wallets_;
  }
  /**
   * <code>repeated .wallet.WalletResponse wallets = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.blockchain.wallet.grpc.WalletResponseOrBuilder> 
      getWalletsOrBuilderList() {
    return wallets_;
  }
  /**
   * <code>repeated .wallet.WalletResponse wallets = 1;</code>
   */
  @java.lang.Override
  public int getWalletsCount() {
    return wallets_.size();
  }
  /**
   * <code>repeated .wallet.WalletResponse wallets = 1;</code>
   */
  @java.lang.Override
  public com.blockchain.wallet.grpc.WalletResponse getWallets(int index) {
    return wallets_.get(index);
  }
  /**
   * <code>repeated .wallet.WalletResponse wallets = 1;</code>
   */
  @java.lang.Override
  public com.blockchain.wallet.grpc.WalletResponseOrBuilder getWalletsOrBuilder(
      int index) {
    return wallets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < wallets_.size(); i++) {
      output.writeMessage(1, wallets_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < wallets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, wallets_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.blockchain.wallet.grpc.GetUserWalletsResponse)) {
      return super.equals(obj);
    }
    com.blockchain.wallet.grpc.GetUserWalletsResponse other = (com.blockchain.wallet.grpc.GetUserWalletsResponse) obj;

    if (!getWalletsList()
        .equals(other.getWalletsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getWalletsCount() > 0) {
      hash = (37 * hash) + WALLETS_FIELD_NUMBER;
      hash = (53 * hash) + getWalletsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.blockchain.wallet.grpc.GetUserWalletsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.wallet.grpc.GetUserWalletsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.wallet.grpc.GetUserWalletsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.wallet.grpc.GetUserWalletsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.wallet.grpc.GetUserWalletsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.wallet.grpc.GetUserWalletsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.wallet.grpc.GetUserWalletsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.wallet.grpc.GetUserWalletsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.blockchain.wallet.grpc.GetUserWalletsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.blockchain.wallet.grpc.GetUserWalletsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blockchain.wallet.grpc.GetUserWalletsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.wallet.grpc.GetUserWalletsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.blockchain.wallet.grpc.GetUserWalletsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wallet.GetUserWalletsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wallet.GetUserWalletsResponse)
      com.blockchain.wallet.grpc.GetUserWalletsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blockchain.wallet.grpc.WalletProto.internal_static_wallet_GetUserWalletsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blockchain.wallet.grpc.WalletProto.internal_static_wallet_GetUserWalletsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blockchain.wallet.grpc.GetUserWalletsResponse.class, com.blockchain.wallet.grpc.GetUserWalletsResponse.Builder.class);
    }

    // Construct using com.blockchain.wallet.grpc.GetUserWalletsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (walletsBuilder_ == null) {
        wallets_ = java.util.Collections.emptyList();
      } else {
        wallets_ = null;
        walletsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.blockchain.wallet.grpc.WalletProto.internal_static_wallet_GetUserWalletsResponse_descriptor;
    }

    @java.lang.Override
    public com.blockchain.wallet.grpc.GetUserWalletsResponse getDefaultInstanceForType() {
      return com.blockchain.wallet.grpc.GetUserWalletsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.blockchain.wallet.grpc.GetUserWalletsResponse build() {
      com.blockchain.wallet.grpc.GetUserWalletsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.blockchain.wallet.grpc.GetUserWalletsResponse buildPartial() {
      com.blockchain.wallet.grpc.GetUserWalletsResponse result = new com.blockchain.wallet.grpc.GetUserWalletsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.blockchain.wallet.grpc.GetUserWalletsResponse result) {
      if (walletsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          wallets_ = java.util.Collections.unmodifiableList(wallets_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.wallets_ = wallets_;
      } else {
        result.wallets_ = walletsBuilder_.build();
      }
    }

    private void buildPartial0(com.blockchain.wallet.grpc.GetUserWalletsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.blockchain.wallet.grpc.GetUserWalletsResponse) {
        return mergeFrom((com.blockchain.wallet.grpc.GetUserWalletsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.blockchain.wallet.grpc.GetUserWalletsResponse other) {
      if (other == com.blockchain.wallet.grpc.GetUserWalletsResponse.getDefaultInstance()) return this;
      if (walletsBuilder_ == null) {
        if (!other.wallets_.isEmpty()) {
          if (wallets_.isEmpty()) {
            wallets_ = other.wallets_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWalletsIsMutable();
            wallets_.addAll(other.wallets_);
          }
          onChanged();
        }
      } else {
        if (!other.wallets_.isEmpty()) {
          if (walletsBuilder_.isEmpty()) {
            walletsBuilder_.dispose();
            walletsBuilder_ = null;
            wallets_ = other.wallets_;
            bitField0_ = (bitField0_ & ~0x00000001);
            walletsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getWalletsFieldBuilder() : null;
          } else {
            walletsBuilder_.addAllMessages(other.wallets_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.blockchain.wallet.grpc.WalletResponse m =
                  input.readMessage(
                      com.blockchain.wallet.grpc.WalletResponse.parser(),
                      extensionRegistry);
              if (walletsBuilder_ == null) {
                ensureWalletsIsMutable();
                wallets_.add(m);
              } else {
                walletsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.blockchain.wallet.grpc.WalletResponse> wallets_ =
      java.util.Collections.emptyList();
    private void ensureWalletsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        wallets_ = new java.util.ArrayList<com.blockchain.wallet.grpc.WalletResponse>(wallets_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.blockchain.wallet.grpc.WalletResponse, com.blockchain.wallet.grpc.WalletResponse.Builder, com.blockchain.wallet.grpc.WalletResponseOrBuilder> walletsBuilder_;

    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public java.util.List<com.blockchain.wallet.grpc.WalletResponse> getWalletsList() {
      if (walletsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(wallets_);
      } else {
        return walletsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public int getWalletsCount() {
      if (walletsBuilder_ == null) {
        return wallets_.size();
      } else {
        return walletsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public com.blockchain.wallet.grpc.WalletResponse getWallets(int index) {
      if (walletsBuilder_ == null) {
        return wallets_.get(index);
      } else {
        return walletsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public Builder setWallets(
        int index, com.blockchain.wallet.grpc.WalletResponse value) {
      if (walletsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWalletsIsMutable();
        wallets_.set(index, value);
        onChanged();
      } else {
        walletsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public Builder setWallets(
        int index, com.blockchain.wallet.grpc.WalletResponse.Builder builderForValue) {
      if (walletsBuilder_ == null) {
        ensureWalletsIsMutable();
        wallets_.set(index, builderForValue.build());
        onChanged();
      } else {
        walletsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public Builder addWallets(com.blockchain.wallet.grpc.WalletResponse value) {
      if (walletsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWalletsIsMutable();
        wallets_.add(value);
        onChanged();
      } else {
        walletsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public Builder addWallets(
        int index, com.blockchain.wallet.grpc.WalletResponse value) {
      if (walletsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWalletsIsMutable();
        wallets_.add(index, value);
        onChanged();
      } else {
        walletsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public Builder addWallets(
        com.blockchain.wallet.grpc.WalletResponse.Builder builderForValue) {
      if (walletsBuilder_ == null) {
        ensureWalletsIsMutable();
        wallets_.add(builderForValue.build());
        onChanged();
      } else {
        walletsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public Builder addWallets(
        int index, com.blockchain.wallet.grpc.WalletResponse.Builder builderForValue) {
      if (walletsBuilder_ == null) {
        ensureWalletsIsMutable();
        wallets_.add(index, builderForValue.build());
        onChanged();
      } else {
        walletsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public Builder addAllWallets(
        java.lang.Iterable<? extends com.blockchain.wallet.grpc.WalletResponse> values) {
      if (walletsBuilder_ == null) {
        ensureWalletsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, wallets_);
        onChanged();
      } else {
        walletsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public Builder clearWallets() {
      if (walletsBuilder_ == null) {
        wallets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        walletsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public Builder removeWallets(int index) {
      if (walletsBuilder_ == null) {
        ensureWalletsIsMutable();
        wallets_.remove(index);
        onChanged();
      } else {
        walletsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public com.blockchain.wallet.grpc.WalletResponse.Builder getWalletsBuilder(
        int index) {
      return getWalletsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public com.blockchain.wallet.grpc.WalletResponseOrBuilder getWalletsOrBuilder(
        int index) {
      if (walletsBuilder_ == null) {
        return wallets_.get(index);  } else {
        return walletsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public java.util.List<? extends com.blockchain.wallet.grpc.WalletResponseOrBuilder> 
         getWalletsOrBuilderList() {
      if (walletsBuilder_ != null) {
        return walletsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(wallets_);
      }
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public com.blockchain.wallet.grpc.WalletResponse.Builder addWalletsBuilder() {
      return getWalletsFieldBuilder().addBuilder(
          com.blockchain.wallet.grpc.WalletResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public com.blockchain.wallet.grpc.WalletResponse.Builder addWalletsBuilder(
        int index) {
      return getWalletsFieldBuilder().addBuilder(
          index, com.blockchain.wallet.grpc.WalletResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .wallet.WalletResponse wallets = 1;</code>
     */
    public java.util.List<com.blockchain.wallet.grpc.WalletResponse.Builder> 
         getWalletsBuilderList() {
      return getWalletsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.blockchain.wallet.grpc.WalletResponse, com.blockchain.wallet.grpc.WalletResponse.Builder, com.blockchain.wallet.grpc.WalletResponseOrBuilder> 
        getWalletsFieldBuilder() {
      if (walletsBuilder_ == null) {
        walletsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.blockchain.wallet.grpc.WalletResponse, com.blockchain.wallet.grpc.WalletResponse.Builder, com.blockchain.wallet.grpc.WalletResponseOrBuilder>(
                wallets_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        wallets_ = null;
      }
      return walletsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wallet.GetUserWalletsResponse)
  }

  // @@protoc_insertion_point(class_scope:wallet.GetUserWalletsResponse)
  private static final com.blockchain.wallet.grpc.GetUserWalletsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.blockchain.wallet.grpc.GetUserWalletsResponse();
  }

  public static com.blockchain.wallet.grpc.GetUserWalletsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetUserWalletsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetUserWalletsResponse>() {
    @java.lang.Override
    public GetUserWalletsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetUserWalletsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetUserWalletsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.blockchain.wallet.grpc.GetUserWalletsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

