// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

// Protobuf Java Version: 3.25.1
package com.blockchain.wallet.grpc;

/**
 * Protobuf type {@code wallet.ImportWalletRequest}
 */
public final class ImportWalletRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wallet.ImportWalletRequest)
    ImportWalletRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ImportWalletRequest.newBuilder() to construct.
  private ImportWalletRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ImportWalletRequest() {
    userId_ = "";
    name_ = "";
    network_ = 0;
    password_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ImportWalletRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.blockchain.wallet.grpc.WalletProto.internal_static_wallet_ImportWalletRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.blockchain.wallet.grpc.WalletProto.internal_static_wallet_ImportWalletRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.blockchain.wallet.grpc.ImportWalletRequest.class, com.blockchain.wallet.grpc.ImportWalletRequest.Builder.class);
  }

  private int importTypeCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object importType_;
  public enum ImportTypeCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    PRIVATE_KEY(5),
    MNEMONIC(6),
    IMPORTTYPE_NOT_SET(0);
    private final int value;
    private ImportTypeCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ImportTypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static ImportTypeCase forNumber(int value) {
      switch (value) {
        case 5: return PRIVATE_KEY;
        case 6: return MNEMONIC;
        case 0: return IMPORTTYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ImportTypeCase
  getImportTypeCase() {
    return ImportTypeCase.forNumber(
        importTypeCase_);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userId_ = "";
  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NETWORK_FIELD_NUMBER = 3;
  private int network_ = 0;
  /**
   * <code>.wallet.NetworkType network = 3;</code>
   * @return The enum numeric value on the wire for network.
   */
  @java.lang.Override public int getNetworkValue() {
    return network_;
  }
  /**
   * <code>.wallet.NetworkType network = 3;</code>
   * @return The network.
   */
  @java.lang.Override public com.blockchain.wallet.grpc.NetworkType getNetwork() {
    com.blockchain.wallet.grpc.NetworkType result = com.blockchain.wallet.grpc.NetworkType.forNumber(network_);
    return result == null ? com.blockchain.wallet.grpc.NetworkType.UNRECOGNIZED : result;
  }

  public static final int PASSWORD_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object password_ = "";
  /**
   * <code>string password = 4;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 4;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRIVATE_KEY_FIELD_NUMBER = 5;
  /**
   * <code>string private_key = 5;</code>
   * @return Whether the privateKey field is set.
   */
  public boolean hasPrivateKey() {
    return importTypeCase_ == 5;
  }
  /**
   * <code>string private_key = 5;</code>
   * @return The privateKey.
   */
  public java.lang.String getPrivateKey() {
    java.lang.Object ref = "";
    if (importTypeCase_ == 5) {
      ref = importType_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (importTypeCase_ == 5) {
        importType_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string private_key = 5;</code>
   * @return The bytes for privateKey.
   */
  public com.google.protobuf.ByteString
      getPrivateKeyBytes() {
    java.lang.Object ref = "";
    if (importTypeCase_ == 5) {
      ref = importType_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (importTypeCase_ == 5) {
        importType_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MNEMONIC_FIELD_NUMBER = 6;
  /**
   * <code>string mnemonic = 6;</code>
   * @return Whether the mnemonic field is set.
   */
  public boolean hasMnemonic() {
    return importTypeCase_ == 6;
  }
  /**
   * <code>string mnemonic = 6;</code>
   * @return The mnemonic.
   */
  public java.lang.String getMnemonic() {
    java.lang.Object ref = "";
    if (importTypeCase_ == 6) {
      ref = importType_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (importTypeCase_ == 6) {
        importType_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string mnemonic = 6;</code>
   * @return The bytes for mnemonic.
   */
  public com.google.protobuf.ByteString
      getMnemonicBytes() {
    java.lang.Object ref = "";
    if (importTypeCase_ == 6) {
      ref = importType_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (importTypeCase_ == 6) {
        importType_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (network_ != com.blockchain.wallet.grpc.NetworkType.ETHEREUM_MAINNET.getNumber()) {
      output.writeEnum(3, network_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, password_);
    }
    if (importTypeCase_ == 5) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, importType_);
    }
    if (importTypeCase_ == 6) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, importType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (network_ != com.blockchain.wallet.grpc.NetworkType.ETHEREUM_MAINNET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, network_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, password_);
    }
    if (importTypeCase_ == 5) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, importType_);
    }
    if (importTypeCase_ == 6) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, importType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.blockchain.wallet.grpc.ImportWalletRequest)) {
      return super.equals(obj);
    }
    com.blockchain.wallet.grpc.ImportWalletRequest other = (com.blockchain.wallet.grpc.ImportWalletRequest) obj;

    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (network_ != other.network_) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!getImportTypeCase().equals(other.getImportTypeCase())) return false;
    switch (importTypeCase_) {
      case 5:
        if (!getPrivateKey()
            .equals(other.getPrivateKey())) return false;
        break;
      case 6:
        if (!getMnemonic()
            .equals(other.getMnemonic())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + NETWORK_FIELD_NUMBER;
    hash = (53 * hash) + network_;
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    switch (importTypeCase_) {
      case 5:
        hash = (37 * hash) + PRIVATE_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getPrivateKey().hashCode();
        break;
      case 6:
        hash = (37 * hash) + MNEMONIC_FIELD_NUMBER;
        hash = (53 * hash) + getMnemonic().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.blockchain.wallet.grpc.ImportWalletRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.wallet.grpc.ImportWalletRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.wallet.grpc.ImportWalletRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.wallet.grpc.ImportWalletRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.wallet.grpc.ImportWalletRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blockchain.wallet.grpc.ImportWalletRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blockchain.wallet.grpc.ImportWalletRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.wallet.grpc.ImportWalletRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.blockchain.wallet.grpc.ImportWalletRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.blockchain.wallet.grpc.ImportWalletRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blockchain.wallet.grpc.ImportWalletRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blockchain.wallet.grpc.ImportWalletRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.blockchain.wallet.grpc.ImportWalletRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wallet.ImportWalletRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wallet.ImportWalletRequest)
      com.blockchain.wallet.grpc.ImportWalletRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blockchain.wallet.grpc.WalletProto.internal_static_wallet_ImportWalletRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blockchain.wallet.grpc.WalletProto.internal_static_wallet_ImportWalletRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blockchain.wallet.grpc.ImportWalletRequest.class, com.blockchain.wallet.grpc.ImportWalletRequest.Builder.class);
    }

    // Construct using com.blockchain.wallet.grpc.ImportWalletRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = "";
      name_ = "";
      network_ = 0;
      password_ = "";
      importTypeCase_ = 0;
      importType_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.blockchain.wallet.grpc.WalletProto.internal_static_wallet_ImportWalletRequest_descriptor;
    }

    @java.lang.Override
    public com.blockchain.wallet.grpc.ImportWalletRequest getDefaultInstanceForType() {
      return com.blockchain.wallet.grpc.ImportWalletRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.blockchain.wallet.grpc.ImportWalletRequest build() {
      com.blockchain.wallet.grpc.ImportWalletRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.blockchain.wallet.grpc.ImportWalletRequest buildPartial() {
      com.blockchain.wallet.grpc.ImportWalletRequest result = new com.blockchain.wallet.grpc.ImportWalletRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.blockchain.wallet.grpc.ImportWalletRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.network_ = network_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.password_ = password_;
      }
    }

    private void buildPartialOneofs(com.blockchain.wallet.grpc.ImportWalletRequest result) {
      result.importTypeCase_ = importTypeCase_;
      result.importType_ = this.importType_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.blockchain.wallet.grpc.ImportWalletRequest) {
        return mergeFrom((com.blockchain.wallet.grpc.ImportWalletRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.blockchain.wallet.grpc.ImportWalletRequest other) {
      if (other == com.blockchain.wallet.grpc.ImportWalletRequest.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.network_ != 0) {
        setNetworkValue(other.getNetworkValue());
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      switch (other.getImportTypeCase()) {
        case PRIVATE_KEY: {
          importTypeCase_ = 5;
          importType_ = other.importType_;
          onChanged();
          break;
        }
        case MNEMONIC: {
          importTypeCase_ = 6;
          importType_ = other.importType_;
          onChanged();
          break;
        }
        case IMPORTTYPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              userId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              network_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              password_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              importTypeCase_ = 5;
              importType_ = s;
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              importTypeCase_ = 6;
              importType_ = s;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int importTypeCase_ = 0;
    private java.lang.Object importType_;
    public ImportTypeCase
        getImportTypeCase() {
      return ImportTypeCase.forNumber(
          importTypeCase_);
    }

    public Builder clearImportType() {
      importTypeCase_ = 0;
      importType_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <code>string user_id = 1;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int network_ = 0;
    /**
     * <code>.wallet.NetworkType network = 3;</code>
     * @return The enum numeric value on the wire for network.
     */
    @java.lang.Override public int getNetworkValue() {
      return network_;
    }
    /**
     * <code>.wallet.NetworkType network = 3;</code>
     * @param value The enum numeric value on the wire for network to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkValue(int value) {
      network_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.NetworkType network = 3;</code>
     * @return The network.
     */
    @java.lang.Override
    public com.blockchain.wallet.grpc.NetworkType getNetwork() {
      com.blockchain.wallet.grpc.NetworkType result = com.blockchain.wallet.grpc.NetworkType.forNumber(network_);
      return result == null ? com.blockchain.wallet.grpc.NetworkType.UNRECOGNIZED : result;
    }
    /**
     * <code>.wallet.NetworkType network = 3;</code>
     * @param value The network to set.
     * @return This builder for chaining.
     */
    public Builder setNetwork(com.blockchain.wallet.grpc.NetworkType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      network_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.NetworkType network = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetwork() {
      bitField0_ = (bitField0_ & ~0x00000004);
      network_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string password = 4;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password = 4;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 4;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      password_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      password_ = getDefaultInstance().getPassword();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string password = 4;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      password_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    /**
     * <code>string private_key = 5;</code>
     * @return Whether the privateKey field is set.
     */
    @java.lang.Override
    public boolean hasPrivateKey() {
      return importTypeCase_ == 5;
    }
    /**
     * <code>string private_key = 5;</code>
     * @return The privateKey.
     */
    @java.lang.Override
    public java.lang.String getPrivateKey() {
      java.lang.Object ref = "";
      if (importTypeCase_ == 5) {
        ref = importType_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (importTypeCase_ == 5) {
          importType_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string private_key = 5;</code>
     * @return The bytes for privateKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPrivateKeyBytes() {
      java.lang.Object ref = "";
      if (importTypeCase_ == 5) {
        ref = importType_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (importTypeCase_ == 5) {
          importType_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string private_key = 5;</code>
     * @param value The privateKey to set.
     * @return This builder for chaining.
     */
    public Builder setPrivateKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      importTypeCase_ = 5;
      importType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string private_key = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrivateKey() {
      if (importTypeCase_ == 5) {
        importTypeCase_ = 0;
        importType_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string private_key = 5;</code>
     * @param value The bytes for privateKey to set.
     * @return This builder for chaining.
     */
    public Builder setPrivateKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      importTypeCase_ = 5;
      importType_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string mnemonic = 6;</code>
     * @return Whether the mnemonic field is set.
     */
    @java.lang.Override
    public boolean hasMnemonic() {
      return importTypeCase_ == 6;
    }
    /**
     * <code>string mnemonic = 6;</code>
     * @return The mnemonic.
     */
    @java.lang.Override
    public java.lang.String getMnemonic() {
      java.lang.Object ref = "";
      if (importTypeCase_ == 6) {
        ref = importType_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (importTypeCase_ == 6) {
          importType_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mnemonic = 6;</code>
     * @return The bytes for mnemonic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMnemonicBytes() {
      java.lang.Object ref = "";
      if (importTypeCase_ == 6) {
        ref = importType_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (importTypeCase_ == 6) {
          importType_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mnemonic = 6;</code>
     * @param value The mnemonic to set.
     * @return This builder for chaining.
     */
    public Builder setMnemonic(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      importTypeCase_ = 6;
      importType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mnemonic = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMnemonic() {
      if (importTypeCase_ == 6) {
        importTypeCase_ = 0;
        importType_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string mnemonic = 6;</code>
     * @param value The bytes for mnemonic to set.
     * @return This builder for chaining.
     */
    public Builder setMnemonicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      importTypeCase_ = 6;
      importType_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wallet.ImportWalletRequest)
  }

  // @@protoc_insertion_point(class_scope:wallet.ImportWalletRequest)
  private static final com.blockchain.wallet.grpc.ImportWalletRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.blockchain.wallet.grpc.ImportWalletRequest();
  }

  public static com.blockchain.wallet.grpc.ImportWalletRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ImportWalletRequest>
      PARSER = new com.google.protobuf.AbstractParser<ImportWalletRequest>() {
    @java.lang.Override
    public ImportWalletRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ImportWalletRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ImportWalletRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.blockchain.wallet.grpc.ImportWalletRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

